// @ts-nocheck
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { DepartmentScreen } from '@/components/dept/department-screen';
import GlassCard from '@/components/common/GlassCard';
import { COLORS } from '@/constants/theme';
import { useDepartment } from '@/providers/department-provider';
export default function DepartmentComplaints(){const router=useRouter();const {profile,complaints}=useDepartment();const [query,setQuery]=useState('');const [status,setStatus]=useState('All');const mine=useMemo(()=>complaints.filter(c=>c.assignedDepartment===profile?.department&&!c.is_deleted&& (status==='All'||c.status===status)&&`${c.title} ${c.ward} ${c.category}`.toLowerCase().includes(query.toLowerCase())),[complaints,profile,query,status]);return <DepartmentScreen title="Department Complaints" tab="complaints"><ScrollView contentContainerStyle={styles.content}><View style={styles.search}><MaterialCommunityIcons name="magnify" size={20} color={COLORS.textMuted}/><TextInput placeholder="Search this department's complaints" placeholderTextColor={COLORS.textMuted} value={query} onChangeText={setQuery} style={styles.input}/></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{['All','Pending','In Progress','Resolved'].map(item=><Pressable key={item} onPress={()=>setStatus(item)} style={[styles.filter,status===item&&styles.filterActive]}><Text style={[styles.filterText,status===item&&styles.filterTextActive]}>{item}</Text></Pressable>)}</ScrollView><Text style={styles.scope}>{mine.length} complaint{mine.length===1?'':'s'} · {profile?.department} · all wards</Text>{mine.map(c=><Pressable key={c.id} onPress={()=>router.push({pathname:'/(dept)/complaint-details',params:{id:c.id}})}><GlassCard style={styles.complaint}><View style={styles.top}><Text style={styles.complaintTitle}>{c.title}</Text><Text style={[styles.priority,{color:c.priority==='Emergency'?'#DC2626':c.priority==='High'?'#F59E0B':COLORS.primary}]}>{c.priority}</Text></View><Text style={styles.meta}>{c.ward} · {c.category}</Text><Text numberOfLines={2} style={styles.description}>{c.description}</Text><View style={styles.bottom}><Text style={styles.id}>{c.id}</Text><Text style={styles.status}>{c.status}</Text></View></GlassCard></Pressable>)}{!mine.length&&<Text style={styles.empty}>No matching department complaints.</Text>}</ScrollView></DepartmentScreen>}
const styles=StyleSheet.create({content:{padding:16,paddingBottom:24,gap:11},search:{height:48,borderRadius:14,borderWidth:1,borderColor:COLORS.border,backgroundColor:COLORS.card,flexDirection:'row',alignItems:'center',paddingHorizontal:13,gap:8},input:{flex:1,color:COLORS.text,fontSize:13},filters:{gap:8},filter:{paddingHorizontal:14,paddingVertical:8,borderRadius:18,backgroundColor:'#EDF1F5'},filterActive:{backgroundColor:COLORS.primary},filterText:{fontSize:12,fontWeight:'700',color:COLORS.textMuted},filterTextActive:{color:COLORS.white},scope:{fontSize:12,color:COLORS.textMuted,fontWeight:'600'},complaint:{padding:14,gap:7},top:{flexDirection:'row',gap:8},complaintTitle:{flex:1,fontSize:14,fontWeight:'800',color:COLORS.text},priority:{fontSize:11,fontWeight:'900'},meta:{fontSize:11.5,color:COLORS.primary,fontWeight:'700'},description:{fontSize:12,color:COLORS.textMuted,lineHeight:17},bottom:{flexDirection:'row',justifyContent:'space-between',borderTopWidth:1,borderTopColor:'#EEF1F4',paddingTop:9},id:{fontSize:11,fontWeight:'700',color:COLORS.textMuted},status:{fontSize:11,fontWeight:'800',color:COLORS.success},empty:{textAlign:'center',color:COLORS.textMuted,marginTop:30}});
