import AsyncStorage from '@react-native-async-storage/async-storage';
import { createContext, PropsWithChildren, useContext, useEffect, useMemo, useState } from 'react';

export type AppLanguage = 'English' | 'Marathi';

const en = {
  // Navigation & Shell
  dashboard: 'Dashboard',
  wardRepresentative: 'Ward Representative',
  today: 'Today',
  // Shared settings labels
  selectLanguage: 'Select Language',
  languageEnglish: 'English',
  languageMarathi: 'मराठी',
  // Common labels
  noComplaints: 'No complaints found',
  wardComplaints: 'Ward Complaints',
  escalatedComplaints: 'Escalated Complaints',
  escalatedDesc: 'Complaints escalated to admin for review',
  noEscalated: 'No escalated complaints at this time.',
  // Announcement (read-only for dept)
  latestNotices: 'Latest Notices',
  noAnnouncements: 'No announcements from admin yet.',
  adminNotices: 'Admin Notices',
  readOnly: 'Published by Main Admin',

  complaintExplorer: 'Complaint Explorer',
  wardWise: 'Ward Wise',
  categoryWise: 'Category Wise',
  departmentWise: 'Department Wise',
  totalComplaints: 'Total Complaints',
  pending: 'Pending',
  inProgress: 'In Progress',
  resolved: 'Resolved',
  escalated: 'Escalated',
  blockedUsers: 'Blocked Users',
  announcements: 'Announcements',
  citizens: 'Citizens',
  nagarsevaks: 'Nagarsevaks',
  departmentOfficers: 'Department Officers',
  departments: 'Departments',
  analytics: 'Analytics',
  reports: 'Reports',
  settings: 'Settings',
  profile: 'Profile',
  logout: 'Logout',
  search: 'Search complaints...',
  filters: 'Filters',
  reset: 'Reset',
  all: 'All',

  // Greetings & Banners
  goodMorning: 'Good Morning,',
  goodAfternoon: 'Good Afternoon,',
  goodEvening: 'Good Evening,',
  goodNight: 'Good Night,',
  welcome: 'Welcome,',
  bannerSubtitle: 'Monitor, manage and resolve citizen complaints efficiently across your ward.',
  viewComplaints: 'View Complaints',
  filed: 'Filed',
  successRate: 'Success rate',

  // Sections
  complaintCategories: 'Complaint Categories',
  latestAnnouncements: 'Latest Announcements',
  priorityComplaints: 'Priority Complaints',
  viewAll: 'View All',
  tapToFilter: "Tap an icon to see that category's complaints.",
  urgentNeedsAttention: 'Complaints that need attention first.',

  // Categories
  all_cat: 'All Categories',
  water: 'Water Supply',
  garbage: 'Garbage Disposal',
  streetlights: 'Street Light',
  road: 'Road Damage',
  gutter: 'Gutter Blockage',
  animals: 'Animal Issues',
  traffic: 'Traffic Congestion',
  drainage: 'Drainage Issues',
  tree: 'Fallen Tree',
  other: 'Other Grievances',

  // Complaint Details & Forms
  complaintDetails: 'Complaint Details',
  citizenInfo: 'Citizen Information',
  name: 'Full Name',
  phone: 'Phone Number',
  locality: 'Locality / Area',
  ward: 'Ward Number',
  photos: 'Grievance Photos',
  uploadPhoto: 'Upload Photo',
  updateStatus: 'Update Grievance Status',
  reopen: 'Reopen (Pending)',
  acceptInProgress: 'Accept / In Progress',
  markResolved: 'Mark Resolved',
  timelineHistory: 'Timeline History',
  addNote: 'Add Note',
  escalateToDept: 'Escalate to Department',
  dateFiled: 'Date Filed',
  noPhotos: 'No photos attached by citizen',
  saveChanges: 'Save Changes',

  // Profile Form & Subtitles
  myProfile: 'My Profile',
  tapToChangePhoto: 'Tap to change profile picture',
  officialDemographics: 'Official Demographics',
  demographicsSubtitle: 'Ward info is attached from your municipal registrations record.',
  email: 'Email Address',
  username: 'Username',
  password: 'Password',
  employeeId: 'Employee ID',
  designation: 'Designation',
  department: 'Department',

  // Settings
  preferences: 'Preferences',
  notifications: 'Notifications',
  appearance: 'Appearance',
  privacyPermissions: 'Privacy & Permissions',
  security: 'Security',
  supportHelp: 'Support & Help',
  helpFAQs: 'Help & FAQs',
  privacyPolicy: 'Privacy Policy',
  termsConditions: 'Terms & Conditions',
  aboutSevaSetu: 'About Seva Setu',
  appVersion: 'App Version',
  changePassword: 'Change Password',
  darkMode: 'Dark Mode',
  language: 'Language',
  appMenu: 'App Menu',
  selectDepartment: 'Select Department',
  departmentSelection: 'Department Selection',
  departmentLogin: 'Department Login',
  departmentAccess: 'Complaint Resolution Access',
  selectYourDepartment: 'Select your department',
  demoCredentials: 'Demo credentials',
  departmentId: 'Department ID',
  signIn: 'Sign In',
  signingIn: 'Signing in…',
  officerDetails: 'Officer Details',
  responsibilities: 'Responsibilities',
  assigned: 'Assigned',
  addRemark: 'Add Remark',
  uploadCompletionPhoto: 'Upload Completion Photo',
  softDelete: 'Soft Delete',
  restore: 'Restore',
  deleteReason: 'Delete Reason',
  deletedComplaints: 'Deleted Complaints',
  activeComplaints: 'Active Complaints',
  deletedBy: 'Deleted By',
  deletedAt: 'Deleted At',
  confirmDelete: 'Confirm Delete',
  enterReason: 'Please enter a reason',
  enterPassword: 'Enter your password',
  forgotPassword: 'Forgot password?',
  showPassword: 'Show Password',
  hidePassword: 'Hide Password',
  allWards: 'All Wards',
  wardFilter: 'Ward Filter',
  complaintId: 'Complaint ID',
  citizenName: 'Citizen Name',
  localityArea: 'Locality / Area',
  category: 'Category',
  priority: 'Priority',
  status: 'Status',
  createdDate: 'Created Date',
  viewDetails: 'View Details',
  restoredSuccess: 'Complaint restored successfully',
  deletedSuccess: 'Complaint soft deleted successfully',
  validationError: 'Validation Error',
  loading: 'Loading...',
  errorInvalidCredentials: 'Invalid Department ID or Password.',
  errorRequired: 'Both fields are required.',
  deptPublicWorks: 'Public Works',
  deptPublicWorksTitle: 'Public Works Department',
  deptPublicWorksSubtitle: 'Baukhana / Public Works Department',
  deptWaterSupply: 'Water Supply',
  deptWaterSupplyTitle: 'Water Supply Department',
  deptWaterSupplySubtitle: 'Pani purvatha / Water Supply Department',
  deptSolidWaste: 'Solid Waste Management',
  deptSolidWasteTitle: 'Solid Waste Management Department',
  deptSolidWasteSubtitle: 'Ghan kachra / Solid Waste Management Department',
  deptSanitationHealth: 'Sanitation & Health',
  deptSanitationHealthTitle: 'Sanitation & Health Department',
  deptSanitationHealthSubtitle: 'Swachhata & Aarogya / Sanitation & Health Department',
  deptDrainageSewerage: 'Drainage & Sewerage',
  deptDrainageSewerageTitle: 'Drainage & Sewerage Department',
  deptDrainageSewerageSubtitle: 'Jalnissaran / Drainage & Sewerage Department',
  nagarsevak: 'Nagarsevak',
  nagaradhyaksha: 'Nagaradhyaksha',
  deptOfficer: 'Department Officer',

  // ── Citizen Portal ────────────────────────────────────────────────────────

  // Bottom Nav
  home: 'Home',
  wardNav: 'Ward',
  complaintsNav: 'Complaints',
  reportNav: 'Report',
  newsNav: 'News',
  profileNav: 'Profile',

  // Dashboard
  sevaSetuTitle: 'SEVA SETU',
  malvanMunicipal: 'Malvan Municipal Council',
  complaintStatistics: 'Complaint statistics',
  recentComplaints: 'Recent complaints',
  wardInformation: 'Ward information',
  latestAnnouncementsTitle: 'Latest announcements',
  emergencyContacts: 'Emergency contacts',
  viewAll2: 'View all',
  noComplaintsYet: 'No complaints filed yet',
  issuesResolved: '% of ward issues resolved',
  residents: '~12,400 residents',
  nagarsevakOffice: 'Nagarsevak Office',
  pending2: 'Pending',
  inProgress2: 'In progress',
  resolved2: 'Resolved',
  successRate2: 'Success rate',
  awaitingAction: 'Awaiting action',
  beingResolved: 'Being resolved',
  taskCompleted: 'Task completed',
  overallRecord: 'Overall record',
  filedCount: 'Filed',
  resolvedCount: 'Resolved',
  successRateShort: 'Success rate',

  // Greetings (citizen)
  goodMorningCitizen: 'Good Morning,',
  goodAfternoonCitizen: 'Good Afternoon,',
  goodEveningCitizen: 'Good Evening,',

  // My Complaints
  myComplaints: 'My Complaints',
  noComplaintsSubmitted: 'No complaints submitted',
  noComplaintsDesc: 'All civic issues reported by you will appear here for tracking and resolution.',
  reportFirstIssue: 'Report Your First Issue',
  activeGrievances: 'Active Tracked Grievances',
  detailsLink: 'Details',

  // Report Complaint
  reportComplaint: 'Report Complaint',
  autoAttachNote: 'Your registered ward and locality details will be attached automatically to this complaint report.',
  selectCategory: 'Select complaint category',
  locationLabel: 'Location',
  locationPlaceholder: 'Enter the exact location of the issue',
  detailedDescription: 'Detailed Description',
  descriptionPlaceholder: 'Provide specific details (landmark, duration, impact) to help resolve this quickly.',
  attachPhoto: 'Attach Proof Photo (Optional)',
  uploadProofPhoto: 'Upload proof photo',
  photoFormats: 'Supports JPG, PNG (Max 5MB)',
  submitComplaint: 'Submit Official Complaint',
  submittingComplaint: 'Submitting complaint…',
  permDenied: 'Permission Denied',
  permDeniedMsg: 'Please grant photo library access to upload a proof image.',
  fileTooLarge: 'File Too Large',
  fileTooLargeMsg: 'Please select an image smaller than 5MB.',
  submitError: 'Error',
  submitErrorMsg: 'Failed to submit complaint. Please check fields.',

  // Category labels (citizen report form)
  catWater: 'Water',
  catGarbage: 'Garbage',
  catStreetLight: 'Street Light',
  catRoad: 'Road',
  catDrainage: 'Drainage',
  catStrayAnimals: 'Stray Animals',
  catTree: 'Tree',
  catOther: 'Other',

  // Complaint Success
  complaintRegistered: 'Complaint Registered',
  complaintRegisteredDesc: 'Your ticket has been logged in the system and forwarded to the municipal grievance desk.',
  officialComplaintId: 'OFFICIAL COMPLAINT ID',
  initialStatus: 'Initial Status',
  pendingAction: 'PENDING ACTION',
  backToDashboard: 'Back to Dashboard',

  // Complaint Detail
  complaintId2: 'COMPLAINT ID',
  attachedPhoto: 'Attached Proof Photo',
  complaintInformation: 'Complaint Information',
  resolutionTimeline: 'Resolution Timeline',
  complaintRegisteredStep: 'Complaint Registered',
  ticketLogged: 'Ticket logged successfully',
  forwardedForReview: 'Forwarded for Review',
  deptReview: 'Department is review/investigation',
  awaitingAssignment: 'Awaiting department assignment',
  awaitingResolution: 'Awaiting final resolution',
  civicTaskCompleted: 'Civic task marked completed',
  categoryLabel: 'Category',
  titleLabel: 'Title',
  descriptionLabel: 'Description',
  wardLabel: 'Ward',
  localityLabel: 'Locality',
  submittedOn: 'Submitted On',
  assignedDept: 'Assigned Dept',

  // Ward Screen
  myWardInfo: 'My Ward Info',
  officialDemographicsLabel: 'OFFICIAL DEMOGRAPHICS',
  wardRepsTitle: 'Ward Representatives (Nagarsevak)',
  callRepBtn: 'Call Ward Representative',
  issuesResolvedLabel: '% issues resolved in this ward',

  // Announcements
  announcementsTitle: 'Announcements',
  municipalNotifications: 'Municipal Board Notifications',
  noticeLabel: 'Notice',

  // Complete Profile
  completeProfile: 'Complete Profile',
  completeProfileDesc: 'Setting up your official ward and locality ensures your complaints are routed to the right desk.',
  fullName: 'Full Name',
  fullNamePlaceholder: 'Enter your full name',
  selectWard: 'Select Ward',
  selectWardHint: 'Select your registered municipal voting ward',
  selectLocality: 'Select Locality',
  selectLocalityHint: 'Choose the specific neighborhood area',
  continueToDashboard: 'Continue to Dashboard',

  // Citizen Login
  citizenLogin: 'Citizen Login',
  enterMobile: 'Enter Mobile Number',
  mobileHint: 'Enter your 10-digit mobile number to receive an OTP.',
  mobileLabel: 'Mobile Number',
  mobilePlaceholder: '10-digit mobile number',
  sendOtp: 'Send OTP',
  sendingOtp: 'Sending OTP…',
  verifyOtp: 'Verify OTP',
  otpSentTo: 'OTP sent to +91 ',
  otpHint: 'Enter the 6-digit OTP.',
  resendIn: 'Resend in ',
  resendOtp: 'Resend OTP',
  resending: 'Resending…',
  verify: 'Verify & Continue',
  verifying: 'Verifying…',
  completeRegistration: 'Complete Registration',
  registerHint: 'Enter your name and select your ward to complete registration.',
  nameLabel: 'Full Name',
  namePlaceholder: 'Your full name (as on Aadhaar)',
  ward2: 'Ward',
  wardPickerHint: 'Select your ward',
  localityPickerHint: 'Select your locality',
  completeBtn: 'Complete Registration',
  completing: 'Completing…',
  mobileError: 'Please enter a valid 10-digit mobile number starting with 6-9',
  otpError: 'Please enter the complete 6-digit OTP.',
  nameError: 'Please enter your full name.',
  wardError: 'Please select your ward.',
  localityError: 'Please select your locality.',

  // Settings (citizen)
  settingsTitle: 'Settings',
  complaintUpdates: 'Complaint updates',
  councilAnnouncements: 'Council announcements',
  smsAlerts: 'SMS alerts',

  // Profile (citizen)
  profileTitle: 'My Profile',
  mobileNumber: 'Mobile Number',
  mobilePlaceholder2: 'e.g. 9876543210',
  localityAreaStreet: 'Locality / Area / Street',
  localityPlaceholder: 'e.g. Wayari Bazaar',
  municipality: 'Municipality',
  saveChangesBtn: 'Save Changes',
  savingChanges: 'Saving changes…',
  logoutBtn: 'Logout',
  loggingOut: 'Logging out…',
  appMenuTitle: 'App Menu',
  helpFaqs: 'Help & FAQs',
  privacyPol: 'Privacy Policy',
  termsCond: 'Terms & Conditions',
  aboutApp: 'About Seva Setu',
  appVer: 'App Version',
  settingsMenu: 'Settings',
};

const mr: Record<keyof typeof en, string> = {
  // Navigation & Shell
  dashboard: 'डॅशबोर्ड',
  wardRepresentative: 'वॉर्ड प्रतिनिधी',
  today: 'आज',
  selectLanguage: 'भाषा निवडा',
  languageEnglish: 'English',
  languageMarathi: 'मराठी',
  noComplaints: 'कोणत्याही तक्रारी आढळल्या नाहीत',
  wardComplaints: 'वॉर्ड तक्रारी',
  escalatedComplaints: 'वर्ग केलेल्या तक्रारी',
  escalatedDesc: 'आढाव्यासाठी प्रशासनाकडे वर्ग केलेल्या तक्रारी',
  noEscalated: 'सध्या कोणत्याही वर्ग केलेल्या तक्रारी नाहीत.',
  latestNotices: 'नवीनतम सूचना',
  noAnnouncements: 'मुख्य प्रशासकाकडून अद्याप कोणत्याही घोषणा नाहीत.',
  adminNotices: 'प्रशासक सूचना',
  readOnly: 'मुख्य प्रशासकाद्वारे प्रकाशित',
  complaintExplorer: 'तक्रार शोधक',
  wardWise: 'वॉर्डनिहाय',
  categoryWise: 'वर्गनिहाय',
  departmentWise: 'विभागनिहाय',
  totalComplaints: 'एकूण तक्रारी',
  pending: 'प्रलंबित',
  inProgress: 'प्रगतीपथावर',
  resolved: 'निकाली',
  escalated: 'वर्ग केलेले',
  blockedUsers: 'ब्लॉक वापरकर्ते',
  announcements: 'घोषणा',
  citizens: 'नागरिक',
  nagarsevaks: 'नगरसेवक',
  departmentOfficers: 'विभाग अधिकारी',
  departments: 'विभाग',
  analytics: 'विश्लेषण',
  reports: 'अहवाल',
  settings: 'सेटिंग्ज',
  profile: 'प्रोफाइल',
  logout: 'लॉगआउट',
  search: 'तक्रारी शोधा...',
  filters: 'फिल्टर्स',
  reset: 'रीसेट',
  all: 'सर्व',

  // Greetings & Banners
  goodMorning: 'शुभ प्रभात,',
  goodAfternoon: 'शुभ दुपार,',
  goodEvening: 'शुभ संध्याकाळ,',
  goodNight: 'शुभ रात्री,',
  welcome: 'स्वागत आहे,',
  bannerSubtitle: 'तुमच्या वॉर्डातील नागरिकांच्या तक्रारींचे कार्यक्षमतेने संनियंत्रण, व्यवस्थापन आणि निराकरण करा.',
  viewComplaints: 'तक्रारी पहा',
  filed: 'दाखल',
  successRate: 'यशस्वी दर',

  // Sections
  complaintCategories: 'तक्रार श्रेणी',
  latestAnnouncements: 'नवीनतम घोषणा',
  priorityComplaints: 'प्राधान्य तक्रारी',
  viewAll: 'सर्व पहा',
  tapToFilter: 'त्या श्रेणीतील तक्रारी पाहण्यासाठी चिन्हावर टॅप करा.',
  urgentNeedsAttention: 'तक्रारी ज्यांवर आधी लक्ष देणे आवश्यक आहे.',

  // Categories
  all_cat: 'सर्व श्रेणी',
  water: 'पाणी पुरवठा',
  garbage: 'कचरा व्यवस्थापन',
  streetlights: 'पथदिवे',
  road: 'रस्ता दुरुस्ती',
  gutter: 'गटार तुंबणे',
  animals: 'प्राण्यांच्या समस्या',
  traffic: 'वाहतूक कोंडी',
  drainage: 'सांडपाणी समस्या',
  tree: 'झाड पडणे',
  other: 'इतर तक्रारी',

  // Complaint Details & Forms
  complaintDetails: 'तक्रार तपशील',
  citizenInfo: 'नागरिक माहिती',
  name: 'पूर्ण नाव',
  phone: 'फोन नंबर',
  locality: 'परिसर / रस्ता',
  ward: 'वॉर्ड क्रमांक',
  photos: 'तक्रार फोटो',
  uploadPhoto: 'फोटो अपलोड करा',
  updateStatus: 'तक्रार स्थिती अद्ययावत करा',
  reopen: 'पुन्हा उघडा (प्रलंबित)',
  acceptInProgress: 'स्वीकारा / प्रगतीपथावर',
  markResolved: 'निकाली काढा',
  timelineHistory: 'टाइमलाइन इतिहास',
  addNote: 'नोंद जोडा',
  escalateToDept: 'विभागाकडे वर्ग करा',
  dateFiled: 'दाखल तारीख',
  noPhotos: 'नागरिकाने फोटो जोडलेले नाहीत',
  saveChanges: 'बदल जतन करा',

  // Profile Form & Subtitles
  myProfile: 'माझी प्रोफाइल',
  tapToChangePhoto: 'प्रोफाइल फोटो बदलण्यासाठी टॅप करा',
  officialDemographics: 'अधिकृत लोकसंख्याशास्त्र',
  demographicsSubtitle: 'वॉर्ड माहिती तुमच्या नगरपरिषद नोंदणीतून जोडलेली आहे.',
  email: 'ईमेल पत्ता',
  username: 'वापरकर्ता नाव',
  password: 'पासवर्ड',
  employeeId: 'कर्मचारी आयडी',
  designation: 'पदनाम',
  department: 'विभाग',

  // Settings
  preferences: 'प्राधान्ये',
  notifications: 'सूचना',
  appearance: 'देखावा',
  privacyPermissions: 'गोपनीयता आणि परवानग्या',
  security: 'सुरक्षा',
  supportHelp: 'मदत व सहाय्य',
  helpFAQs: 'मदत व विचारले जाणारे प्रश्न',
  privacyPolicy: 'गोपनीयता धोरण',
  termsConditions: 'अटी व शर्ती',
  aboutSevaSetu: 'सेवा सेतू बद्दल',
  appVersion: 'अ‍ॅप आवृत्ती',
  changePassword: 'पासवर्ड बदला',
  darkMode: 'गडद थीम',
  language: 'भाषा',
  appMenu: 'अॅप मेनू',
  selectDepartment: 'विभाग निवडा',
  departmentSelection: 'विभाग निवड',
  departmentLogin: 'विभाग लॉगिन',
  departmentAccess: 'तक्रार निराकरण प्रवेश',
  selectYourDepartment: 'आपला विभाग निवडा',
  demoCredentials: 'डेमो क्रेडेंशियल्स',
  departmentId: 'विभाग आयडी',
  signIn: 'साइन इन',
  signingIn: 'साइन इन होत आहे…',
  officerDetails: 'अधिकारी तपशील',
  responsibilities: 'जबाबदाऱ्या',
  assigned: 'नियुक्त',
  addRemark: 'शेरा जोडा',
  uploadCompletionPhoto: 'पूर्णतेचा फोटो अपलोड करा',
  softDelete: 'काढून टाका (Soft Delete)',
  restore: 'पुनर्संचयित करा',
  deleteReason: 'हटवण्याचे कारण',
  deletedComplaints: 'हटवलेल्या तक्रारी',
  activeComplaints: 'सक्रिय तक्रारी',
  deletedBy: 'कोणाद्वारे हटवले',
  deletedAt: 'कधी हटवले',
  confirmDelete: 'हटवण्याची पुष्टी करा',
  enterReason: 'कृपया कारण प्रविष्ट करा',
  enterPassword: 'पासवर्ड प्रविष्ट करा',
  forgotPassword: 'पासवर्ड विसरलात?',
  showPassword: 'पासवर्ड दाखवा',
  hidePassword: 'पासवर्ड लपवा',
  allWards: 'सर्व वॉर्ड',
  wardFilter: 'वॉर्ड फिल्टर',
  complaintId: 'तक्रार आयडी',
  citizenName: 'नागरिकाचे नाव',
  localityArea: 'परिसर / क्षेत्र',
  category: 'श्रेणी',
  priority: 'प्राधान्य',
  status: 'स्थिती',
  createdDate: 'तयार तारीख',
  viewDetails: 'तपशील पहा',
  restoredSuccess: 'तक्रार यशस्वीरित्या पुनर्संचयित केली',
  deletedSuccess: 'तक्रार यशस्वीरित्या सॉफ्ट डिलीट केली',
  validationError: 'वैधता त्रुटी',
  loading: 'लोड होत आहे...',
  errorInvalidCredentials: 'अवैध विभाग आयडी किंवा पासवर्ड.',
  errorRequired: 'दोन्ही फील्ड आवश्यक आहेत.',
  deptPublicWorks: 'बांधकाम विभाग',
  deptPublicWorksTitle: 'बांधकाम विभाग',
  deptPublicWorksSubtitle: 'सार्वजनिक कार्य विभाग',
  deptWaterSupply: 'पाणीपुरवठा विभाग',
  deptWaterSupplyTitle: 'पाणीपुरवठा विभाग',
  deptWaterSupplySubtitle: 'पाणी पुरवठा विभाग',
  deptSolidWaste: 'घनकचरा व्यवस्थापन विभाग',
  deptSolidWasteTitle: 'घनकचरा व्यवस्थापन विभाग',
  deptSolidWasteSubtitle: 'घनकचरा व्यवस्थापन विभाग',
  deptSanitationHealth: 'स्वच्छता व आरोग्य विभाग',
  deptSanitationHealthTitle: 'स्वच्छता व आरोग्य विभाग',
  deptSanitationHealthSubtitle: 'स्वच्छता व आरोग्य विभाग',
  deptDrainageSewerage: 'जलनिस्सारण व गटार विभाग',
  deptDrainageSewerageTitle: 'जलनिस्सारण व गटार विभाग',
  deptDrainageSewerageSubtitle: 'जलनिस्सारण व गटार विभाग',
  nagarsevak: 'नगरसेवक',
  nagaradhyaksha: 'नगराध्यक्ष',
  deptOfficer: 'विभाग अधिकारी',

  // ── Citizen Portal ────────────────────────────────────────────────────────

  // Bottom Nav
  home: 'मुखपृष्ठ',
  wardNav: 'वॉर्ड',
  complaintsNav: 'तक्रारी',
  reportNav: 'नोंदवा',
  newsNav: 'बातम्या',
  profileNav: 'प्रोफाइल',

  // Dashboard
  sevaSetuTitle: 'सेवा सेतू',
  malvanMunicipal: 'मालवण नगरपरिषद',
  complaintStatistics: 'तक्रार आकडेवारी',
  recentComplaints: 'अलीकडील तक्रारी',
  wardInformation: 'वॉर्ड माहिती',
  latestAnnouncementsTitle: 'नवीनतम घोषणा',
  emergencyContacts: 'आणीबाणी संपर्क',
  viewAll2: 'सर्व पहा',
  noComplaintsYet: 'अद्याप कोणत्याही तक्रारी दाखल नाहीत',
  issuesResolved: '% वॉर्ड समस्या सोडवल्या',
  residents: '~१२,४०० रहिवासी',
  nagarsevakOffice: 'नगरसेवक कार्यालय',
  pending2: 'प्रलंबित',
  inProgress2: 'प्रगतीपथावर',
  resolved2: 'निकाली',
  successRate2: 'यशस्वी दर',
  awaitingAction: 'कारवाईच्या प्रतीक्षेत',
  beingResolved: 'सोडवले जात आहे',
  taskCompleted: 'काम पूर्ण',
  overallRecord: 'एकूण नोंद',
  filedCount: 'दाखल',
  resolvedCount: 'निकाली',
  successRateShort: 'यशस्वी दर',

  // Greetings (citizen)
  goodMorningCitizen: 'शुभ प्रभात,',
  goodAfternoonCitizen: 'शुभ दुपार,',
  goodEveningCitizen: 'शुभ संध्याकाळ,',

  // My Complaints
  myComplaints: 'माझ्या तक्रारी',
  noComplaintsSubmitted: 'कोणत्याही तक्रारी दाखल नाहीत',
  noComplaintsDesc: 'तुम्ही नोंदवलेल्या सर्व नागरी समस्या येथे ट्रॅकिंग आणि निराकरणासाठी दिसतील.',
  reportFirstIssue: 'पहिली समस्या नोंदवा',
  activeGrievances: 'सक्रिय ट्रॅक केलेल्या तक्रारी',
  detailsLink: 'तपशील',

  // Report Complaint
  reportComplaint: 'तक्रार नोंदवा',
  autoAttachNote: 'तुमच्या नोंदणीकृत वॉर्ड आणि परिसराचे तपशील या तक्रार अहवालात आपोआप जोडले जातील.',
  selectCategory: 'तक्रार श्रेणी निवडा',
  locationLabel: 'ठिकाण',
  locationPlaceholder: 'समस्येचे अचूक ठिकाण प्रविष्ट करा',
  detailedDescription: 'सविस्तर वर्णन',
  descriptionPlaceholder: 'विशिष्ट तपशील द्या (खूण, कालावधी, परिणाम) जेणेकरून हे लवकर सोडवता येईल.',
  attachPhoto: 'पुरावा फोटो जोडा (पर्यायी)',
  uploadProofPhoto: 'पुरावा फोटो अपलोड करा',
  photoFormats: 'JPG, PNG ला सपोर्ट करतो (जास्तीत जास्त 5MB)',
  submitComplaint: 'अधिकृत तक्रार सादर करा',
  submittingComplaint: 'तक्रार सादर होत आहे…',
  permDenied: 'परवानगी नाकारली',
  permDeniedMsg: 'पुरावा प्रतिमा अपलोड करण्यासाठी फोटो लायब्ररीला प्रवेश द्या.',
  fileTooLarge: 'फाइल खूप मोठी',
  fileTooLargeMsg: '5MB पेक्षा लहान प्रतिमा निवडा.',
  submitError: 'त्रुटी',
  submitErrorMsg: 'तक्रार सादर करणे अयशस्वी. कृपया फील्ड तपासा.',

  // Category labels (citizen report form)
  catWater: 'पाणी',
  catGarbage: 'कचरा',
  catStreetLight: 'पथदिवा',
  catRoad: 'रस्ता',
  catDrainage: 'सांडपाणी',
  catStrayAnimals: 'भटके प्राणी',
  catTree: 'झाड',
  catOther: 'इतर',

  // Complaint Success
  complaintRegistered: 'तक्रार नोंदणी झाली',
  complaintRegisteredDesc: 'तुमचे तिकीट प्रणालीत नोंदवले गेले आहे आणि नगरपालिका तक्रार डेस्ककडे पाठवले आहे.',
  officialComplaintId: 'अधिकृत तक्रार आयडी',
  initialStatus: 'प्रारंभिक स्थिती',
  pendingAction: 'कारवाई प्रलंबित',
  backToDashboard: 'डॅशबोर्डवर परत',

  // Complaint Detail
  complaintId2: 'तक्रार आयडी',
  attachedPhoto: 'जोडलेला पुरावा फोटो',
  complaintInformation: 'तक्रार माहिती',
  resolutionTimeline: 'निराकरण टाइमलाइन',
  complaintRegisteredStep: 'तक्रार नोंदणी झाली',
  ticketLogged: 'तिकीट यशस्वीरित्या नोंदवले',
  forwardedForReview: 'आढाव्यासाठी पाठवले',
  deptReview: 'विभाग आढावा/तपास करत आहे',
  awaitingAssignment: 'विभाग नियुक्तीच्या प्रतीक्षेत',
  awaitingResolution: 'अंतिम निराकरणाच्या प्रतीक्षेत',
  civicTaskCompleted: 'नागरी काम पूर्ण म्हणून चिन्हांकित',
  categoryLabel: 'श्रेणी',
  titleLabel: 'शीर्षक',
  descriptionLabel: 'वर्णन',
  wardLabel: 'वॉर्ड',
  localityLabel: 'परिसर',
  submittedOn: 'सादर केले',
  assignedDept: 'नियुक्त विभाग',

  // Ward Screen
  myWardInfo: 'माझी वॉर्ड माहिती',
  officialDemographicsLabel: 'अधिकृत लोकसंख्याशास्त्र',
  wardRepsTitle: 'वॉर्ड प्रतिनिधी (नगरसेवक)',
  callRepBtn: 'वॉर्ड प्रतिनिधींना कॉल करा',
  issuesResolvedLabel: '% समस्या या वॉर्डात सोडवल्या',

  // Announcements
  announcementsTitle: 'घोषणा',
  municipalNotifications: 'नगरपालिका मंडळाच्या सूचना',
  noticeLabel: 'सूचना',

  // Complete Profile
  completeProfile: 'प्रोफाइल पूर्ण करा',
  completeProfileDesc: 'तुमचा अधिकृत वॉर्ड आणि परिसर सेट केल्याने तुमच्या तक्रारी योग्य डेस्ककडे पाठवल्या जातात.',
  fullName: 'पूर्ण नाव',
  fullNamePlaceholder: 'तुमचे पूर्ण नाव प्रविष्ट करा',
  selectWard: 'वॉर्ड निवडा',
  selectWardHint: 'तुमचा नोंदणीकृत नगरपालिका मतदान वॉर्ड निवडा',
  selectLocality: 'परिसर निवडा',
  selectLocalityHint: 'विशिष्ट शेजारचा परिसर निवडा',
  continueToDashboard: 'डॅशबोर्डवर सुरू ठेवा',

  // Citizen Login
  citizenLogin: 'नागरिक लॉगिन',
  enterMobile: 'मोबाइल क्रमांक प्रविष्ट करा',
  mobileHint: 'OTP प्राप्त करण्यासाठी तुमचा 10-अंकी मोबाइल क्रमांक प्रविष्ट करा.',
  mobileLabel: 'मोबाइल क्रमांक',
  mobilePlaceholder: '10-अंकी मोबाइल क्रमांक',
  sendOtp: 'OTP पाठवा',
  sendingOtp: 'OTP पाठवत आहे…',
  verifyOtp: 'OTP सत्यापित करा',
  otpSentTo: 'OTP पाठवला +91 ',
  otpHint: '6-अंकी OTP प्रविष्ट करा.',
  resendIn: 'पुन्हा पाठवा ',
  resendOtp: 'OTP पुन्हा पाठवा',
  resending: 'पाठवत आहे…',
  verify: 'सत्यापित करा आणि सुरू ठेवा',
  verifying: 'सत्यापित होत आहे…',
  completeRegistration: 'नोंदणी पूर्ण करा',
  registerHint: 'नोंदणी पूर्ण करण्यासाठी तुमचे नाव प्रविष्ट करा आणि वॉर्ड निवडा.',
  nameLabel: 'पूर्ण नाव',
  namePlaceholder: 'तुमचे पूर्ण नाव (आधारप्रमाणे)',
  ward2: 'वॉर्ड',
  wardPickerHint: 'तुमचा वॉर्ड निवडा',
  localityPickerHint: 'तुमचा परिसर निवडा',
  completeBtn: 'नोंदणी पूर्ण करा',
  completing: 'पूर्ण होत आहे…',
  mobileError: 'कृपया 6-9 ने सुरू होणारा वैध 10-अंकी मोबाइल क्रमांक प्रविष्ट करा',
  otpError: 'कृपया संपूर्ण 6-अंकी OTP प्रविष्ट करा.',
  nameError: 'कृपया तुमचे पूर्ण नाव प्रविष्ट करा.',
  wardError: 'कृपया तुमचा वॉर्ड निवडा.',
  localityError: 'कृपया तुमचा परिसर निवडा.',

  // Settings (citizen)
  settingsTitle: 'सेटिंग्ज',
  complaintUpdates: 'तक्रार अद्यतने',
  councilAnnouncements: 'परिषद घोषणा',
  smsAlerts: 'SMS सूचना',

  // Profile (citizen)
  profileTitle: 'माझी प्रोफाइल',
  mobileNumber: 'मोबाइल क्रमांक',
  mobilePlaceholder2: 'उदा. 9876543210',
  localityAreaStreet: 'परिसर / क्षेत्र / रस्ता',
  localityPlaceholder: 'उदा. वायरी बाजार',
  municipality: 'नगरपालिका',
  saveChangesBtn: 'बदल जतन करा',
  savingChanges: 'बदल जतन होत आहेत…',
  logoutBtn: 'लॉगआउट',
  loggingOut: 'लॉगआउट होत आहे…',
  appMenuTitle: 'अॅप मेनू',
  helpFaqs: 'मदत व विचारले जाणारे प्रश्न',
  privacyPol: 'गोपनीयता धोरण',
  termsCond: 'अटी व शर्ती',
  aboutApp: 'सेवा सेतू बद्दल',
  appVer: 'अॅप आवृत्ती',
  settingsMenu: 'सेटिंग्ज',
};

const KEY = '@seva-setu/language';

type Value = {
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => Promise<void>;
  t: (key: string) => string;
};

const LocalizationContext = createContext<Value | undefined>(undefined);

export function LocalizationProvider({ children }: PropsWithChildren) {
  const [language, setLanguageState] = useState<AppLanguage>('English');

  useEffect(() => {
    void AsyncStorage.getItem(KEY).then((saved) => {
      if (saved === 'Marathi' || saved === 'English') {
        setLanguageState(saved);
      }
    });
  }, []);

  const setLanguage = async (next: AppLanguage) => {
    setLanguageState(next);
    await AsyncStorage.setItem(KEY, next);
  };

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key: string) => {
        const transKey = key as keyof typeof en;
        return (language === 'Marathi' ? mr[transKey] : en[transKey]) || en[transKey] || key;
      },
    }),
    [language]
  );

  return <LocalizationContext.Provider value={value}>{children}</LocalizationContext.Provider>;
}

export function useTranslation() {
  const context = useContext(LocalizationContext);
  if (!context) {
    throw new Error('useTranslation must be used inside LocalizationProvider.');
  }
  return context;
}
