import AsyncStorage from '@react-native-async-storage/async-storage';
import { createContext, PropsWithChildren, useContext, useEffect, useMemo, useState } from 'react';

export type AppLanguage = 'English' | 'Marathi';

const en = {
  // Navigation & Shell
  dashboard: 'Dashboard',
  wardRepresentative: 'Ward Representative',
  today: 'Today',
  // Shared settings labels
  selectLanguage: 'Select Language',
  languageEnglish: 'English',
  languageMarathi: 'मराठी',
  // Common labels
  noComplaints: 'No complaints found',
  wardComplaints: 'Ward Complaints',
  escalatedComplaints: 'Escalated Complaints',
  escalatedDesc: 'Complaints escalated to admin for review',
  noEscalated: 'No escalated complaints at this time.',
  // Announcement (read-only for dept)
  latestNotices: 'Latest Notices',
  noAnnouncements: 'No announcements from admin yet.',
  adminNotices: 'Admin Notices',
  readOnly: 'Published by Main Admin',

  complaintExplorer: 'Complaint Explorer',
  wardWise: 'Ward Wise',
  categoryWise: 'Category Wise',
  departmentWise: 'Department Wise',
  totalComplaints: 'Total Complaints',
  pending: 'Pending',
  inProgress: 'In Progress',
  resolved: 'Resolved',
  escalated: 'Escalated',
  blockedUsers: 'Blocked Users',
  announcements: 'Announcements',
  citizens: 'Citizens',
  nagarsevaks: 'Nagarsevaks',
  departmentOfficers: 'Department Officers',
  departments: 'Departments',
  analytics: 'Analytics',
  reports: 'Reports',
  settings: 'Settings',
  profile: 'Profile',
  logout: 'Logout',
  search: 'Search complaints...',
  filters: 'Filters',
  reset: 'Reset',
  all: 'All',

  // Greetings & Banners
  goodMorning: 'Good Morning,',
  goodAfternoon: 'Good Afternoon,',
  goodEvening: 'Good Evening,',
  goodNight: 'Good Night,',
  welcome: 'Welcome,',
  bannerSubtitle: 'Monitor, manage and resolve citizen complaints efficiently across your ward.',
  viewComplaints: 'View Complaints',
  filed: 'Filed',
  successRate: 'Success rate',

  // Sections
  complaintCategories: 'Complaint Categories',
  latestAnnouncements: 'Latest Announcements',
  priorityComplaints: 'Priority Complaints',
  viewAll: 'View All',
  tapToFilter: "Tap an icon to see that category's complaints.",
  urgentNeedsAttention: 'Complaints that need attention first.',

  // Categories
  all_cat: 'All Categories',
  water: 'Water Supply',
  garbage: 'Garbage Disposal',
  streetlights: 'Street Light',
  road: 'Road Damage',
  gutter: 'Gutter Blockage',
  animals: 'Animal Issues',
  traffic: 'Traffic Congestion',
  drainage: 'Drainage Issues',
  tree: 'Fallen Tree',
  other: 'Other Grievances',

  // Complaint Details & Forms
  complaintDetails: 'Complaint Details',
  citizenInfo: 'Citizen Information',
  name: 'Full Name',
  phone: 'Phone Number',
  locality: 'Locality / Area',
  ward: 'Ward Number',
  photos: 'Grievance Photos',
  uploadPhoto: 'Upload Photo',
  updateStatus: 'Update Grievance Status',
  reopen: 'Reopen (Pending)',
  acceptInProgress: 'Accept / In Progress',
  markResolved: 'Mark Resolved',
  timelineHistory: 'Timeline History',
  addNote: 'Add Note',
  escalateToDept: 'Escalate to Department',
  dateFiled: 'Date Filed',
  noPhotos: 'No photos attached by citizen',
  saveChanges: 'Save Changes',

  // Profile Form & Subtitles
  myProfile: 'My Profile',
  tapToChangePhoto: 'Tap to change profile picture',
  officialDemographics: 'Official Demographics',
  demographicsSubtitle: 'Ward info is attached from your municipal registrations record.',
  email: 'Email Address',
  username: 'Username',
  password: 'Password',
  employeeId: 'Employee ID',
  designation: 'Designation',
  department: 'Department',

  // Settings
  preferences: 'Preferences',
  notifications: 'Notifications',
  appearance: 'Appearance',
  privacyPermissions: 'Privacy & Permissions',
  security: 'Security',
  supportHelp: 'Support & Help',
  helpFAQs: 'Help & FAQs',
  privacyPolicy: 'Privacy Policy',
  termsConditions: 'Terms & Conditions',
  aboutSevaSetu: 'About Seva Setu',
  appVersion: 'App Version',
  themeLight: 'Light',
  themeDark: 'Dark',
  themeSystem: 'System',
  cancel: 'Cancel',
  logoutConfirmation: 'Are you sure you want to log out?',
  logoutCitizenConfirmation: 'Log out from Seva Setu?',
  logoutDepartmentConfirmation: 'Sign out of the Department Officer Portal?',
  restrictedPortal: 'Restricted Portal',
  restrictedAccess: 'RESTRICTED ACCESS',
  tapToFill: 'Tap to fill',
  secureEncryption: 'Secured with 256-bit encryption',
  unableToSignIn: 'Unable to sign in.',
  enterOtp: 'Enter OTP',
  change: 'Change',
  canResendNow: 'You can resend now',
  createCitizenProfile: 'Create citizen profile',
  addressVerificationHint: 'Please provide details matching your official address in Malvan.',
  localityStreetLandmark: 'Locality / Street / Landmark',
  localityExample: 'e.g. Medha, Wayari Road',
  selectResidenceWard: 'Please choose the municipal ward of your residence.',
  officialId: 'Official ID',
  officialIdPlaceholder: 'Enter official ID',
  enterWard: 'Enter ward',
  departmentLoginHint: 'Choose your department, then sign in with authorised credentials.',
  municipalDepartment: 'Municipal Department',
  demoCredentialsTapToFill: 'Demo Credentials — Tap to fill',
  usernamePlaceholder: 'Enter username',
  error: 'Error',
  success: 'Success',
  profileUpdatedToast: 'Profile updated successfully.',
  profileUpdateFailed: 'Failed to update profile.',
  changePassword: 'Change Password',
  darkMode: 'Dark Mode',
  language: 'Language',
  appMenu: 'App Menu',
  selectDepartment: 'Select Department',
  departmentSelection: 'Department Selection',
  departmentLogin: 'Department Login',
  departmentAccess: 'Complaint Resolution Access',
  selectYourDepartment: 'Select your department',
  demoCredentials: 'Demo credentials',
  departmentId: 'Department ID',
  signIn: 'Sign In',
  signingIn: 'Signing in…',
  officerDetails: 'Officer Details',
  responsibilities: 'Responsibilities',
  assigned: 'Assigned',
  addRemark: 'Add Remark',
  uploadCompletionPhoto: 'Upload Completion Photo',
  softDelete: 'Soft Delete',
  restore: 'Restore',
  deleteReason: 'Delete Reason',
  deletedComplaints: 'Deleted Complaints',
  activeComplaints: 'Active Complaints',
  deletedBy: 'Deleted By',
  deletedAt: 'Deleted At',
  confirmDelete: 'Confirm Delete',
  enterReason: 'Please enter a reason',
  enterPassword: 'Enter your password',
  forgotPassword: 'Forgot password?',
  showPassword: 'Show Password',
  hidePassword: 'Hide Password',
  allWards: 'All Wards',
  wardFilter: 'Ward Filter',
  complaintId: 'Complaint ID',
  citizenName: 'Citizen Name',
  localityArea: 'Locality / Area',
  category: 'Category',
  priority: 'Priority',
  status: 'Status',
  createdDate: 'Created Date',
  viewDetails: 'View Details',
  restoredSuccess: 'Complaint restored successfully',
  deletedSuccess: 'Complaint soft deleted successfully',
  validationError: 'Validation Error',
  loading: 'Loading...',
  errorInvalidCredentials: 'Invalid Department ID or Password.',
  errorRequired: 'Both fields are required.',
  deptPublicWorks: 'Public Works',
  deptPublicWorksTitle: 'Public Works Department',
  deptPublicWorksSubtitle: 'Baukhana / Public Works Department',
  deptWaterSupply: 'Water Supply',
  deptWaterSupplyTitle: 'Water Supply Department',
  deptWaterSupplySubtitle: 'Pani purvatha / Water Supply Department',
  deptSolidWaste: 'Solid Waste Management',
  deptSolidWasteTitle: 'Solid Waste Management Department',
  deptSolidWasteSubtitle: 'Ghan kachra / Solid Waste Management Department',
  deptSanitationHealth: 'Sanitation & Health',
  deptSanitationHealthTitle: 'Sanitation & Health Department',
  deptSanitationHealthSubtitle: 'Swachhata & Aarogya / Sanitation & Health Department',
  deptDrainageSewerage: 'Drainage & Sewerage',
  deptDrainageSewerageTitle: 'Drainage & Sewerage Department',
  deptDrainageSewerageSubtitle: 'Jalnissaran / Drainage & Sewerage Department',
  nagarsevak: 'Nagarsevak',
  nagaradhyaksha: 'Nagaradhyaksha',
  deptOfficer: 'Department Officer',

  // ── Citizen Portal ────────────────────────────────────────────────────────

  // Bottom Nav
  home: 'Home',
  wardNav: 'Ward',
  complaintsNav: 'Complaints',
  reportNav: 'Report',
  newsNav: 'News',
  profileNav: 'Profile',

  // Dashboard
  sevaSetuTitle: 'SEVA SETU',
  malvanMunicipal: 'Malvan Municipal Council',
  complaintStatistics: 'Complaint statistics',
  recentComplaints: 'Recent complaints',
  wardInformation: 'Ward information',
  latestAnnouncementsTitle: 'Latest announcements',
  emergencyContacts: 'Emergency contacts',
  viewAll2: 'View all',
  noComplaintsYet: 'No complaints filed yet',
  issuesResolved: '% of ward issues resolved',
  residents: '~12,400 residents',
  nagarsevakOffice: 'Nagarsevak Office',
  pending2: 'Pending',
  inProgress2: 'In progress',
  resolved2: 'Resolved',
  successRate2: 'Success rate',
  awaitingAction: 'Awaiting action',
  beingResolved: 'Being resolved',
  taskCompleted: 'Task completed',
  overallRecord: 'Overall record',
  filedCount: 'Filed',
  resolvedCount: 'Resolved',
  successRateShort: 'Success rate',

  // Greetings (citizen)
  goodMorningCitizen: 'Good Morning,',
  goodAfternoonCitizen: 'Good Afternoon,',
  goodEveningCitizen: 'Good Evening,',

  // My Complaints
  myComplaints: 'My Complaints',
  noComplaintsSubmitted: 'No complaints submitted',
  noComplaintsDesc: 'All civic issues reported by you will appear here for tracking and resolution.',
  reportFirstIssue: 'Report Your First Issue',
  activeGrievances: 'Active Tracked Grievances',
  detailsLink: 'Details',

  // Report Complaint
  reportComplaint: 'Report Complaint',
  autoAttachNote: 'Your registered ward and locality details will be attached automatically to this complaint report.',
  selectCategory: 'Select complaint category',
  locationLabel: 'Location',
  locationPlaceholder: 'Enter the exact location of the issue',
  detailedDescription: 'Detailed Description',
  descriptionPlaceholder: 'Provide specific details (landmark, duration, impact) to help resolve this quickly.',
  attachPhoto: 'Attach Proof Photo (Optional)',
  uploadProofPhoto: 'Upload proof photo',
  photoFormats: 'Supports JPG, PNG (Max 5MB)',
  submitComplaint: 'Submit Official Complaint',
  submittingComplaint: 'Submitting complaint…',
  permDenied: 'Permission Denied',
  permDeniedMsg: 'Please grant photo library access to upload a proof image.',
  fileTooLarge: 'File Too Large',
  fileTooLargeMsg: 'Please select an image smaller than 5MB.',
  submitError: 'Error',
  submitErrorMsg: 'Failed to submit complaint. Please check fields.',

  // Category labels (citizen report form)
  catWater: 'Water',
  catGarbage: 'Garbage',
  catStreetLight: 'Street Light',
  catRoad: 'Road',
  catDrainage: 'Drainage',
  catStrayAnimals: 'Stray Animals',
  catTree: 'Tree',
  catOther: 'Other',

  // Complaint Success
  complaintRegistered: 'Complaint Registered',
  complaintRegisteredDesc: 'Your ticket has been logged in the system and forwarded to the municipal grievance desk.',
  officialComplaintId: 'OFFICIAL COMPLAINT ID',
  initialStatus: 'Initial Status',
  pendingAction: 'PENDING ACTION',
  backToDashboard: 'Back to Dashboard',

  // Complaint Detail
  complaintId2: 'COMPLAINT ID',
  attachedPhoto: 'Attached Proof Photo',
  complaintInformation: 'Complaint Information',
  resolutionTimeline: 'Resolution Timeline',
  complaintRegisteredStep: 'Complaint Registered',
  ticketLogged: 'Ticket logged successfully',
  forwardedForReview: 'Forwarded for Review',
  deptReview: 'Department is review/investigation',
  awaitingAssignment: 'Awaiting department assignment',
  awaitingResolution: 'Awaiting final resolution',
  civicTaskCompleted: 'Civic task marked completed',
  categoryLabel: 'Category',
  titleLabel: 'Title',
  descriptionLabel: 'Description',
  wardLabel: 'Ward',
  localityLabel: 'Locality',
  submittedOn: 'Submitted On',
  assignedDept: 'Assigned Dept',

  // Ward Screen
  myWardInfo: 'My Ward Info',
  officialDemographicsLabel: 'OFFICIAL DEMOGRAPHICS',
  wardRepsTitle: 'Ward Representatives (Nagarsevak)',
  callRepBtn: 'Call Ward Representative',
  issuesResolvedLabel: '% issues resolved in this ward',

  // Announcements
  announcementsTitle: 'Announcements',
  municipalNotifications: 'Municipal Board Notifications',
  noticeLabel: 'Notice',

  // Complete Profile
  completeProfile: 'Complete Profile',
  completeProfileDesc: 'Setting up your official ward and locality ensures your complaints are routed to the right desk.',
  fullName: 'Full Name',
  fullNamePlaceholder: 'Enter your full name',
  selectWard: 'Select Ward',
  selectWardHint: 'Select your registered municipal voting ward',
  selectLocality: 'Select Locality',
  selectLocalityHint: 'Choose the specific neighborhood area',
  continueToDashboard: 'Continue to Dashboard',

  // Citizen Login
  citizenLogin: 'Citizen Login',
  enterMobile: 'Enter Mobile Number',
  mobileHint: 'Enter your 10-digit mobile number to receive an OTP.',
  mobileLabel: 'Mobile Number',
  mobilePlaceholder: '10-digit mobile number',
  sendOtp: 'Send OTP',
  sendingOtp: 'Sending OTP…',
  verifyOtp: 'Verify OTP',
  otpSentTo: 'OTP sent to +91 ',
  otpHint: 'Enter the 6-digit OTP.',
  resendIn: 'Resend in ',
  resendOtp: 'Resend OTP',
  resending: 'Resending…',
  verify: 'Verify & Continue',
  verifying: 'Verifying…',
  completeRegistration: 'Complete Registration',
  registerHint: 'Enter your name and select your ward to complete registration.',
  nameLabel: 'Full Name',
  namePlaceholder: 'Your full name (as on Aadhaar)',
  ward2: 'Ward',
  wardPickerHint: 'Select your ward',
  localityPickerHint: 'Select your locality',
  completeBtn: 'Complete Registration',
  completing: 'Completing…',
  mobileError: 'Please enter a valid 10-digit mobile number starting with 6-9',
  otpError: 'Please enter the complete 6-digit OTP.',
  nameError: 'Please enter your full name.',
  wardError: 'Please select your ward.',
  localityError: 'Please select your locality.',

  // Settings (citizen)
  settingsTitle: 'Settings',
  complaintUpdates: 'Complaint updates',
  councilAnnouncements: 'Council announcements',
  smsAlerts: 'SMS alerts',

  // Profile (citizen)
  profileTitle: 'My Profile',
  mobileNumber: 'Mobile Number',
  mobilePlaceholder2: 'e.g. 9876543210',
  localityAreaStreet: 'Locality / Area / Street',
  localityPlaceholder: 'e.g. Wayari Bazaar',
  municipality: 'Municipality',
  saveChangesBtn: 'Save Changes',
  savingChanges: 'Saving changes…',
  logoutBtn: 'Logout',
  loggingOut: 'Logging out…',
  appMenuTitle: 'App Menu',
  helpFaqs: 'Help & FAQs',
  privacyPol: 'Privacy Policy',
  termsCond: 'Terms & Conditions',
  aboutApp: 'About Seva Setu',
  appVer: 'App Version',
  settingsMenu: 'Settings',

  // ── Auth / Splash ─────────────────────────────────────────────────────────
  splashSlogan: 'Connecting Citizens. Solving Problems.',
  splashSkip: 'Skip →',

  // ── Role Selection ────────────────────────────────────────────────────────
  welcomeMalvan: 'Welcome to Malvan',
  roleSelectHint: 'Select your login profile to connect with municipal services.',
  roleCitizen: 'Citizen Login',
  roleCitizenDesc: 'Report issues & track progress',
  roleNagarsevak: 'Nagarsevak Login',
  roleNagarsevakDesc: 'Representative governance portal',
  roleDepartment: 'Department Login',
  roleDepartmentDesc: 'Resolve assigned civic reports',
  roleAdmin: 'Admin Login',
  roleAdminDesc: 'Municipal control & settings',

  // ── Admin Login ───────────────────────────────────────────────────────────
  adminLoginHint: 'Use authorised credentials to access the Nagaradhyaksha portal.',
  adminId: 'Admin ID',
  adminIdPlaceholder: 'Enter Admin ID',
  loginToAdminPortal: 'Login to Admin Portal',
  securedEncryption: 'Secured with 256-bit encryption',

  // ── Nagarsevak Login ──────────────────────────────────────────────────────
  nagarsevakLogin: 'Nagarsevak Login',
  nagarsevakLoginSubtitle: 'Access the ward-level municipal dashboard.',
  signInToContinue: 'Sign in to continue',
  nagarsevakLoginHint: 'Use your ward officer credentials to open the nagarsevak portal.',
  wardLabel2: 'Ward',
  wardPlaceholder: 'Enter ward',
  passwordLabel: 'Password',
  passwordPlaceholder: 'Enter password',
  login: 'Login',

  // ── Official / Nagarsevak Dashboard ───────────────────────────────────────
  wardOverview: 'Ward Overview',
  performanceGlance: 'Performance at a glance',
  todaysUpdates: "Today's Updates",
  monthlyPerformance: 'Monthly Performance',
  avgResolution: 'Avg. Resolution',
  emergencyHighPriority: 'Emergency & High priority',
  allClear: 'All clear!',
  noUrgentComplaints: 'No urgent complaints pending right now.',
  nagarsevakDesignation: 'Nagarsevak (Ward Representative)',
  municipalAlerts: 'Municipal alerts and council notices',
  noAnnouncementsTab: 'No announcements',
  noNoticesTime: 'There are no {tab} notices at this time.',

  // ── Official Complaints screen ────────────────────────────────────────────
  wardComplaintsTitle: 'Ward Complaints',
  nagarsevakWardReview: 'Nagarsevak ward review',
  searchPlaceholderOfficial: 'Search by ID, title, citizen or location…',
  noMatchingComplaints: 'No matching complaints',
  adjustFilters: 'Try adjusting your search or filters.',
  complaintsFound: 'complaints found',
  complaintFound: 'complaint found',

  // ── Official Complaint Details ─────────────────────────────────────────────
  complaintSummary: 'Complaint Summary',
  complaintNotFound: 'Complaint not found',
  complaintNotFoundDesc: 'The grievance reference ID does not exist in this ward.',
  goBack: 'Go Back',
  filedOn: 'Filed',
  updatedOn: 'Updated',
  citizenInformation: 'Citizen Information',
  complaintDetailsSection: 'Complaint Details',
  attachedPhotos: 'Attached Photos',
  uploadBtn: 'Upload',
  noPhotosYet: 'No photos attached yet.',
  timeline: 'Timeline',
  addNoteBtn: 'Add note',
  notes: 'Notes',
  actions: 'Actions',
  escalateComplaint: 'Escalate Complaint',
  complaintRegisteredEvent: 'Complaint registered',
  assignedToDept: 'Assigned to department',
  routedTo: 'Routed to',
  actionTaken: 'Action taken',
  successUpload: 'Success',
  successUploadMsg: 'Verification photo uploaded.',
  statusUpdated: 'Updated',
  statusUpdatedMsg: 'Status set to',

  // ── Official Profile ───────────────────────────────────────────────────────
  tapToChangeProfilePic: 'Tap to change profile picture',
  officialDemographicsSection: 'Official Demographics',
  roleAndWardNote: 'Role and ward info is attached from your municipal registration record.',
  saving: 'Saving…',
  saveChangesProfile: 'Save Changes',
  loggingOutLabel: 'Logging out…',
  logoutLabel: 'Logout',
  validationTitle: 'Validation',
  nameRequired: 'Full name is required.',
  phoneRequired: 'Phone number is required.',
  profileUpdated: 'Profile updated successfully.',
  profileUpdateError: 'Failed to save profile. Please try again.',
  photoUploadNote: 'Photo picker will be available after backend integration.',

  // ── Official Settings ─────────────────────────────────────────────────────
  grievanceAssignments: 'Grievance Assignments',
  grievanceAssignmentsDesc: 'Alert when a citizen files a complaint in your ward.',
  councilAnnouncementsLabel: 'Council Announcements',
  councilAnnouncementsDesc: 'Alert when Main Admin publishes a notice.',
  smsAlertBroadcasts: 'SMS Alert Broadcasts',
  smsAlertBroadcastsDesc: 'Text notifications for emergency alerts.',
  weeklyEmailSummary: 'Weekly Email Summary',
  weeklyEmailSummaryDesc: 'Digest of ward resolution statistics every week.',
  alertPreferences: 'Alert Preferences',
  selectTheme: 'Select Theme',
  accessibilityLabel: 'Accessibility',
  highContrastMode: 'High Contrast Mode',
  highContrastDesc: 'Increases text contrast for better legibility.',
  reduceMotion: 'Reduce Motion',
  reduceMotionDesc: 'Disables slide-in animations and transitions.',
  generalSettings: 'General Settings',
  biometricAuth: 'Biometric Authentication',
  biometricDesc: 'Use FaceID/Fingerprint to login quickly.',
  autoLogout: 'Auto Logout Session',
  autoLogoutDesc: 'Log out after 30 minutes of inactivity.',

  // ── About Screen ──────────────────────────────────────────────────────────
  officialGovernancePortal: 'Official Governance Portal · v1.0.0',
  connectingMalvan: 'Connecting Malvan',
  connectingMalvanBody1: 'Seva Setu is the official digital bridge linking the citizens of Malvan with their elected ward representatives (Nagarsevaks) and municipal administration officers.',
  connectingMalvanBody2: 'By leveraging local ward demographics and real-time grievance logs, the portal ensures administrative accountability, public transparency, and accelerated resolution times for civic tasks.',
  officialRecognition: 'Official Recognition',
  officialRecognitionBody: 'This application node is synchronized directly with the desks of the Malvan Municipal Council. All activities, grievance reports, and performance parameters are securely logged under public administrative monitoring norms.',
  citizenGrievanceNode: 'Citizen Grievance Resolution Node • v1.0.0',
  connectingMalvanCitizen: 'Connecting Malvan',
  connectingMalvanCitizenBody: 'Seva Setu serves as the official communication bridge between Malvan citizens and the Municipal Administration. By reporting localized ward issues, citizens empower the municipality to act swiftly and maintain local infrastructure with absolute transparency.',
  officialCouncilNode: 'Official Council Node',
  officialCouncilNodeBody: 'All complaints, data, and tracking are directly synchronized with the Malvan Municipal Council desks. Access is governed under official public data protection norms.',
  meetOurTeam: 'Meet Our Team',
  meetOurTeamSub: 'The people behind Seva Setu, working to make Malvan\'s civic services simpler and faster.',
  footerCopyright: '© 2026 Malvan Municipal Council • Government of Maharashtra',

  // ── Admin Dashboard ───────────────────────────────────────────────────────
  liveStats: 'Live City Stats',
  realTimeOverview: 'Real-time municipal overview',
  exploreComplaints: 'Explore Complaints',
  drillData: 'Drill into city-wide data',
  quickActions: 'Quick Actions',
  viewAllComplaints: 'View All Complaints',
  bestWards: 'Best Wards',
  performanceRanking: 'Performance ranking',
  wardWiseLabel: 'Ward Wise',
  allMunicipalWards: 'All 10 municipal wards',
  categoryWiseLabel: 'Category Wise',
  byIssueType: 'By issue type',
  departmentWiseLabel: 'Department Wise',
  resolutionByDept: 'Resolution by dept.',

  // ── Admin Announcements ───────────────────────────────────────────────────
  announcementsScreen: 'Announcements',
  composeTab: 'Compose',
  publishedTab: 'Published',
  announcementTitle: 'Announcement Title',
  announcementTitlePlaceholder: 'Enter a clear, concise title…',
  messageBody: 'Message Body',
  messageBodyPlaceholder: 'Full announcement text…',
  priorityLevel: 'Priority Level',
  targetAudience: 'Target Audience',
  sendAnnouncement: 'Send Announcement',
  noAnnouncementsYet: 'No announcements yet',
  missingInfo: 'Missing information',
  fillTitleMessage: 'Please fill in both the title and message.',
  scheduleComingSoon: 'Schedule (coming soon)',
  attachFile: 'Attach file',
  previewLabel: 'Preview',
  hidePreview: 'Hide preview',

  // ── Admin Complaints ──────────────────────────────────────────────────────
  searchComplaintsAdmin: 'Search by ID, title, citizen, location…',
  noMatchingComplaintsAdmin: 'No matching complaints',
  adjustFiltersAdmin: 'Adjust your search or filters.',
  addNoteTitle: 'Add Note',
  restrictUser: 'Restrict User',
  blockUser: 'Block User',
  removeComplaint: 'Remove Complaint',
  confirmAction: 'Confirm',

  // ── Department Dashboard ──────────────────────────────────────────────────
  welcomeBack: 'Welcome back,',
  allWardsWorkspace: 'All 10 wards · Department workspace',
  filterByWard: 'Filter by Ward',
  tapWardFilter: 'Tap a ward to view its complaints. Tap again to clear.',
  allWardsChip: 'All Wards',
  resolutionRate: 'Resolution Rate',
  resolvedOf: 'resolved out of',
  total: 'total',
  pendingComplaints: 'Pending Complaints',
  allCaughtUp: 'All caught up!',
  noPendingComplaints: 'No pending complaints',
  rightNow: 'right now.',
  reviewAllComplaints: 'Review All Complaints',
  deptOnlyReporting: 'Department-only reporting · all wards',
  monthlyPerformanceLabel: 'Monthly performance',

  // ── Department Complaints ─────────────────────────────────────────────────
  searchDeptComplaints: "Search this department's complaints",
  deptComplaintsScope: 'all wards',
  noDeptComplaints: 'No matching department complaints.',

  // ── Department Announcements ──────────────────────────────────────────────
  readOnlyNotice: 'Notices published by Main Admin (Nagaradhyaksha) · Read-only',
  noAnnouncementsMsg: 'No announcements',
  noNoticesPublished: 'No {tab} notices have been published yet.',

  // ── Ward Screen ────────────────────────────────────────────────────────────
  officialDemographicsHeader: 'OFFICIAL DEMOGRAPHICS',
  wardRepsSection: 'Ward Representatives (Nagarsevak)',
  callWardRep: 'Call Ward Representative',
  issuesResolvedWard: '% issues resolved in this ward',

  // ── Leaderboard ───────────────────────────────────────────────────────────
  wardLeaderboard: 'Ward Leaderboard',
  leaderboardTitle: 'Clean & Swift Ward rankings',
  leaderboardBody: 'Wards are ranked dynamically based on resolution rates, public cleanliness ratings, and feedback logs.',
  rankLabel: 'Rank',
  wardRepLabel: 'Ward & Representative',
  resolutionRateLabel: 'Res. Rate',

  // ── Help Screen ───────────────────────────────────────────────────────────
  helpSupport: 'Help & Support',
  frequentlyAsked: 'Frequently Asked Questions',
  howToReportTrack: 'How to Report & Track',
  contactMunicipalCouncil: 'Contact Municipal Council',
  contactIntro: 'If you need direct assistance regarding ward issues or general municipal services, please reach out below.',
  callSupport: 'Call Support: 02365-252018',
  emailSupport: 'Email: support@malvanmunicipal.in',
  portalFooter: 'Malvan Municipal Council Seva Setu Portal v1.0.0',

  // ── Dept Help FAQs ────────────────────────────────────────────────────────
  tapToExpand: 'Tap any question to expand the answer.',
};

const mr: Record<keyof typeof en, string> = {
  // Navigation & Shell
  dashboard: 'डॅशबोर्ड',
  wardRepresentative: 'वॉर्ड प्रतिनिधी',
  today: 'आज',
  selectLanguage: 'भाषा निवडा',
  languageEnglish: 'English',
  languageMarathi: 'मराठी',
  noComplaints: 'कोणत्याही तक्रारी आढळल्या नाहीत',
  wardComplaints: 'वॉर्ड तक्रारी',
  escalatedComplaints: 'वर्ग केलेल्या तक्रारी',
  escalatedDesc: 'आढाव्यासाठी प्रशासनाकडे वर्ग केलेल्या तक्रारी',
  noEscalated: 'सध्या कोणत्याही वर्ग केलेल्या तक्रारी नाहीत.',
  latestNotices: 'नवीनतम सूचना',
  noAnnouncements: 'मुख्य प्रशासकाकडून अद्याप कोणत्याही घोषणा नाहीत.',
  adminNotices: 'प्रशासक सूचना',
  readOnly: 'मुख्य प्रशासकाद्वारे प्रकाशित',
  complaintExplorer: 'तक्रार शोधक',
  wardWise: 'वॉर्डनिहाय',
  categoryWise: 'वर्गनिहाय',
  departmentWise: 'विभागनिहाय',
  totalComplaints: 'एकूण तक्रारी',
  pending: 'प्रलंबित',
  inProgress: 'प्रगतीपथावर',
  resolved: 'निकाली',
  escalated: 'वर्ग केलेले',
  blockedUsers: 'ब्लॉक वापरकर्ते',
  announcements: 'घोषणा',
  citizens: 'नागरिक',
  nagarsevaks: 'नगरसेवक',
  departmentOfficers: 'विभाग अधिकारी',
  departments: 'विभाग',
  analytics: 'विश्लेषण',
  reports: 'अहवाल',
  settings: 'सेटिंग्ज',
  profile: 'प्रोफाइल',
  logout: 'लॉगआउट',
  search: 'तक्रारी शोधा...',
  filters: 'फिल्टर्स',
  reset: 'रीसेट',
  all: 'सर्व',

  // Greetings & Banners
  goodMorning: 'शुभ प्रभात,',
  goodAfternoon: 'शुभ दुपार,',
  goodEvening: 'शुभ संध्याकाळ,',
  goodNight: 'शुभ रात्री,',
  welcome: 'स्वागत आहे,',
  bannerSubtitle: 'तुमच्या वॉर्डातील नागरिकांच्या तक्रारींचे कार्यक्षमतेने संनियंत्रण, व्यवस्थापन आणि निराकरण करा.',
  viewComplaints: 'तक्रारी पहा',
  filed: 'दाखल',
  successRate: 'यशस्वी दर',

  // Sections
  complaintCategories: 'तक्रार श्रेणी',
  latestAnnouncements: 'नवीनतम घोषणा',
  priorityComplaints: 'प्राधान्य तक्रारी',
  viewAll: 'सर्व पहा',
  tapToFilter: 'त्या श्रेणीतील तक्रारी पाहण्यासाठी चिन्हावर टॅप करा.',
  urgentNeedsAttention: 'तक्रारी ज्यांवर आधी लक्ष देणे आवश्यक आहे.',

  // Categories
  all_cat: 'सर्व श्रेणी',
  water: 'पाणी पुरवठा',
  garbage: 'कचरा व्यवस्थापन',
  streetlights: 'पथदिवे',
  road: 'रस्ता दुरुस्ती',
  gutter: 'गटार तुंबणे',
  animals: 'प्राण्यांच्या समस्या',
  traffic: 'वाहतूक कोंडी',
  drainage: 'सांडपाणी समस्या',
  tree: 'झाड पडणे',
  other: 'इतर तक्रारी',

  // Complaint Details & Forms
  complaintDetails: 'तक्रार तपशील',
  citizenInfo: 'नागरिक माहिती',
  name: 'पूर्ण नाव',
  phone: 'फोन नंबर',
  locality: 'परिसर / रस्ता',
  ward: 'वॉर्ड क्रमांक',
  photos: 'तक्रार फोटो',
  uploadPhoto: 'फोटो अपलोड करा',
  updateStatus: 'तक्रार स्थिती अद्ययावत करा',
  reopen: 'पुन्हा उघडा (प्रलंबित)',
  acceptInProgress: 'स्वीकारा / प्रगतीपथावर',
  markResolved: 'निकाली काढा',
  timelineHistory: 'टाइमलाइन इतिहास',
  addNote: 'नोंद जोडा',
  escalateToDept: 'विभागाकडे वर्ग करा',
  dateFiled: 'दाखल तारीख',
  noPhotos: 'नागरिकाने फोटो जोडलेले नाहीत',
  saveChanges: 'बदल जतन करा',

  // Profile Form & Subtitles
  myProfile: 'माझी प्रोफाइल',
  tapToChangePhoto: 'प्रोफाइल फोटो बदलण्यासाठी टॅप करा',
  officialDemographics: 'अधिकृत लोकसंख्याशास्त्र',
  demographicsSubtitle: 'वॉर्ड माहिती तुमच्या नगरपरिषद नोंदणीतून जोडलेली आहे.',
  email: 'ईमेल पत्ता',
  username: 'वापरकर्ता नाव',
  password: 'पासवर्ड',
  employeeId: 'कर्मचारी आयडी',
  designation: 'पदनाम',
  department: 'विभाग',

  // Settings
  preferences: 'प्राधान्ये',
  notifications: 'सूचना',
  appearance: 'देखावा',
  privacyPermissions: 'गोपनीयता आणि परवानग्या',
  security: 'सुरक्षा',
  supportHelp: 'मदत व सहाय्य',
  helpFAQs: 'मदत व विचारले जाणारे प्रश्न',
  privacyPolicy: 'गोपनीयता धोरण',
  termsConditions: 'अटी व शर्ती',
  aboutSevaSetu: 'सेवा सेतू बद्दल',
  appVersion: 'अ‍ॅप आवृत्ती',
  changePassword: 'पासवर्ड बदला',
  darkMode: 'गडद थीम',
  language: 'भाषा',
  appMenu: 'अॅप मेनू',
  selectDepartment: 'विभाग निवडा',
  departmentSelection: 'विभाग निवड',
  departmentLogin: 'विभाग लॉगिन',
  departmentAccess: 'तक्रार निराकरण प्रवेश',
  selectYourDepartment: 'आपला विभाग निवडा',
  demoCredentials: 'डेमो क्रेडेंशियल्स',
  departmentId: 'विभाग आयडी',
  signIn: 'साइन इन',
  signingIn: 'साइन इन होत आहे…',
  officerDetails: 'अधिकारी तपशील',
  responsibilities: 'जबाबदाऱ्या',
  assigned: 'नियुक्त',
  addRemark: 'शेरा जोडा',
  uploadCompletionPhoto: 'पूर्णतेचा फोटो अपलोड करा',
  softDelete: 'काढून टाका (Soft Delete)',
  restore: 'पुनर्संचयित करा',
  deleteReason: 'हटवण्याचे कारण',
  deletedComplaints: 'हटवलेल्या तक्रारी',
  activeComplaints: 'सक्रिय तक्रारी',
  deletedBy: 'कोणाद्वारे हटवले',
  deletedAt: 'कधी हटवले',
  confirmDelete: 'हटवण्याची पुष्टी करा',
  enterReason: 'कृपया कारण प्रविष्ट करा',
  enterPassword: 'पासवर्ड प्रविष्ट करा',
  forgotPassword: 'पासवर्ड विसरलात?',
  showPassword: 'पासवर्ड दाखवा',
  hidePassword: 'पासवर्ड लपवा',
  allWards: 'सर्व वॉर्ड',
  wardFilter: 'वॉर्ड फिल्टर',
  complaintId: 'तक्रार आयडी',
  citizenName: 'नागरिकाचे नाव',
  localityArea: 'परिसर / क्षेत्र',
  category: 'श्रेणी',
  priority: 'प्राधान्य',
  status: 'स्थिती',
  createdDate: 'तयार तारीख',
  viewDetails: 'तपशील पहा',
  restoredSuccess: 'तक्रार यशस्वीरित्या पुनर्संचयित केली',
  deletedSuccess: 'तक्रार यशस्वीरित्या सॉफ्ट डिलीट केली',
  validationError: 'वैधता त्रुटी',
  loading: 'लोड होत आहे...',
  errorInvalidCredentials: 'अवैध विभाग आयडी किंवा पासवर्ड.',
  errorRequired: 'दोन्ही फील्ड आवश्यक आहेत.',
  deptPublicWorks: 'बांधकाम विभाग',
  deptPublicWorksTitle: 'बांधकाम विभाग',
  deptPublicWorksSubtitle: 'सार्वजनिक कार्य विभाग',
  deptWaterSupply: 'पाणीपुरवठा विभाग',
  deptWaterSupplyTitle: 'पाणीपुरवठा विभाग',
  deptWaterSupplySubtitle: 'पाणी पुरवठा विभाग',
  deptSolidWaste: 'घनकचरा व्यवस्थापन विभाग',
  deptSolidWasteTitle: 'घनकचरा व्यवस्थापन विभाग',
  deptSolidWasteSubtitle: 'घनकचरा व्यवस्थापन विभाग',
  deptSanitationHealth: 'स्वच्छता व आरोग्य विभाग',
  deptSanitationHealthTitle: 'स्वच्छता व आरोग्य विभाग',
  deptSanitationHealthSubtitle: 'स्वच्छता व आरोग्य विभाग',
  deptDrainageSewerage: 'जलनिस्सारण व गटार विभाग',
  deptDrainageSewerageTitle: 'जलनिस्सारण व गटार विभाग',
  deptDrainageSewerageSubtitle: 'जलनिस्सारण व गटार विभाग',
  nagarsevak: 'नगरसेवक',
  nagaradhyaksha: 'नगराध्यक्ष',
  deptOfficer: 'विभाग अधिकारी',

  // ── Citizen Portal ────────────────────────────────────────────────────────

  // Bottom Nav
  home: 'मुखपृष्ठ',
  wardNav: 'वॉर्ड',
  complaintsNav: 'तक्रारी',
  reportNav: 'नोंदवा',
  newsNav: 'बातम्या',
  profileNav: 'प्रोफाइल',

  // Dashboard
  sevaSetuTitle: 'सेवा सेतू',
  malvanMunicipal: 'मालवण नगरपरिषद',
  complaintStatistics: 'तक्रार आकडेवारी',
  recentComplaints: 'अलीकडील तक्रारी',
  wardInformation: 'वॉर्ड माहिती',
  latestAnnouncementsTitle: 'नवीनतम घोषणा',
  emergencyContacts: 'आणीबाणी संपर्क',
  viewAll2: 'सर्व पहा',
  noComplaintsYet: 'अद्याप कोणत्याही तक्रारी दाखल नाहीत',
  issuesResolved: '% वॉर्ड समस्या सोडवल्या',
  residents: '~१२,४०० रहिवासी',
  nagarsevakOffice: 'नगरसेवक कार्यालय',
  pending2: 'प्रलंबित',
  inProgress2: 'प्रगतीपथावर',
  resolved2: 'निकाली',
  successRate2: 'यशस्वी दर',
  awaitingAction: 'कारवाईच्या प्रतीक्षेत',
  beingResolved: 'सोडवले जात आहे',
  taskCompleted: 'काम पूर्ण',
  overallRecord: 'एकूण नोंद',
  filedCount: 'दाखल',
  resolvedCount: 'निकाली',
  successRateShort: 'यशस्वी दर',

  // Greetings (citizen)
  goodMorningCitizen: 'शुभ प्रभात,',
  goodAfternoonCitizen: 'शुभ दुपार,',
  goodEveningCitizen: 'शुभ संध्याकाळ,',

  // My Complaints
  myComplaints: 'माझ्या तक्रारी',
  noComplaintsSubmitted: 'कोणत्याही तक्रारी दाखल नाहीत',
  noComplaintsDesc: 'तुम्ही नोंदवलेल्या सर्व नागरी समस्या येथे ट्रॅकिंग आणि निराकरणासाठी दिसतील.',
  reportFirstIssue: 'पहिली समस्या नोंदवा',
  activeGrievances: 'सक्रिय ट्रॅक केलेल्या तक्रारी',
  detailsLink: 'तपशील',

  // Report Complaint
  reportComplaint: 'तक्रार नोंदवा',
  autoAttachNote: 'तुमच्या नोंदणीकृत वॉर्ड आणि परिसराचे तपशील या तक्रार अहवालात आपोआप जोडले जातील.',
  selectCategory: 'तक्रार श्रेणी निवडा',
  locationLabel: 'ठिकाण',
  locationPlaceholder: 'समस्येचे अचूक ठिकाण प्रविष्ट करा',
  detailedDescription: 'सविस्तर वर्णन',
  descriptionPlaceholder: 'विशिष्ट तपशील द्या (खूण, कालावधी, परिणाम) जेणेकरून हे लवकर सोडवता येईल.',
  attachPhoto: 'पुरावा फोटो जोडा (पर्यायी)',
  uploadProofPhoto: 'पुरावा फोटो अपलोड करा',
  photoFormats: 'JPG, PNG ला सपोर्ट करतो (जास्तीत जास्त 5MB)',
  submitComplaint: 'अधिकृत तक्रार सादर करा',
  submittingComplaint: 'तक्रार सादर होत आहे…',
  permDenied: 'परवानगी नाकारली',
  permDeniedMsg: 'पुरावा प्रतिमा अपलोड करण्यासाठी फोटो लायब्ररीला प्रवेश द्या.',
  fileTooLarge: 'फाइल खूप मोठी',
  fileTooLargeMsg: '5MB पेक्षा लहान प्रतिमा निवडा.',
  submitError: 'त्रुटी',
  submitErrorMsg: 'तक्रार सादर करणे अयशस्वी. कृपया फील्ड तपासा.',

  // Category labels (citizen report form)
  catWater: 'पाणी',
  catGarbage: 'कचरा',
  catStreetLight: 'पथदिवा',
  catRoad: 'रस्ता',
  catDrainage: 'सांडपाणी',
  catStrayAnimals: 'भटके प्राणी',
  catTree: 'झाड',
  catOther: 'इतर',

  // Complaint Success
  complaintRegistered: 'तक्रार नोंदणी झाली',
  complaintRegisteredDesc: 'तुमचे तिकीट प्रणालीत नोंदवले गेले आहे आणि नगरपालिका तक्रार डेस्ककडे पाठवले आहे.',
  officialComplaintId: 'अधिकृत तक्रार आयडी',
  initialStatus: 'प्रारंभिक स्थिती',
  pendingAction: 'कारवाई प्रलंबित',
  backToDashboard: 'डॅशबोर्डवर परत',

  // Complaint Detail
  complaintId2: 'तक्रार आयडी',
  attachedPhoto: 'जोडलेला पुरावा फोटो',
  complaintInformation: 'तक्रार माहिती',
  resolutionTimeline: 'निराकरण टाइमलाइन',
  complaintRegisteredStep: 'तक्रार नोंदणी झाली',
  ticketLogged: 'तिकीट यशस्वीरित्या नोंदवले',
  forwardedForReview: 'आढाव्यासाठी पाठवले',
  deptReview: 'विभाग आढावा/तपास करत आहे',
  awaitingAssignment: 'विभाग नियुक्तीच्या प्रतीक्षेत',
  awaitingResolution: 'अंतिम निराकरणाच्या प्रतीक्षेत',
  civicTaskCompleted: 'नागरी काम पूर्ण म्हणून चिन्हांकित',
  categoryLabel: 'श्रेणी',
  titleLabel: 'शीर्षक',
  descriptionLabel: 'वर्णन',
  wardLabel: 'वॉर्ड',
  localityLabel: 'परिसर',
  submittedOn: 'सादर केले',
  assignedDept: 'नियुक्त विभाग',

  // Ward Screen
  myWardInfo: 'माझी वॉर्ड माहिती',
  officialDemographicsLabel: 'अधिकृत लोकसंख्याशास्त्र',
  wardRepsTitle: 'वॉर्ड प्रतिनिधी (नगरसेवक)',
  callRepBtn: 'वॉर्ड प्रतिनिधींना कॉल करा',
  issuesResolvedLabel: '% समस्या या वॉर्डात सोडवल्या',

  // Announcements
  announcementsTitle: 'घोषणा',
  municipalNotifications: 'नगरपालिका मंडळाच्या सूचना',
  noticeLabel: 'सूचना',

  // Complete Profile
  completeProfile: 'प्रोफाइल पूर्ण करा',
  completeProfileDesc: 'तुमचा अधिकृत वॉर्ड आणि परिसर सेट केल्याने तुमच्या तक्रारी योग्य डेस्ककडे पाठवल्या जातात.',
  fullName: 'पूर्ण नाव',
  fullNamePlaceholder: 'तुमचे पूर्ण नाव प्रविष्ट करा',
  selectWard: 'वॉर्ड निवडा',
  selectWardHint: 'तुमचा नोंदणीकृत नगरपालिका मतदान वॉर्ड निवडा',
  selectLocality: 'परिसर निवडा',
  selectLocalityHint: 'विशिष्ट शेजारचा परिसर निवडा',
  continueToDashboard: 'डॅशबोर्डवर सुरू ठेवा',

  // Citizen Login
  citizenLogin: 'नागरिक लॉगिन',
  enterMobile: 'मोबाइल क्रमांक प्रविष्ट करा',
  mobileHint: 'OTP प्राप्त करण्यासाठी तुमचा 10-अंकी मोबाइल क्रमांक प्रविष्ट करा.',
  mobileLabel: 'मोबाइल क्रमांक',
  mobilePlaceholder: '10-अंकी मोबाइल क्रमांक',
  sendOtp: 'OTP पाठवा',
  sendingOtp: 'OTP पाठवत आहे…',
  verifyOtp: 'OTP सत्यापित करा',
  otpSentTo: 'OTP पाठवला +91 ',
  otpHint: '6-अंकी OTP प्रविष्ट करा.',
  resendIn: 'पुन्हा पाठवा ',
  resendOtp: 'OTP पुन्हा पाठवा',
  resending: 'पाठवत आहे…',
  verify: 'सत्यापित करा आणि सुरू ठेवा',
  verifying: 'सत्यापित होत आहे…',
  completeRegistration: 'नोंदणी पूर्ण करा',
  registerHint: 'नोंदणी पूर्ण करण्यासाठी तुमचे नाव प्रविष्ट करा आणि वॉर्ड निवडा.',
  nameLabel: 'पूर्ण नाव',
  namePlaceholder: 'तुमचे पूर्ण नाव (आधारप्रमाणे)',
  ward2: 'वॉर्ड',
  wardPickerHint: 'तुमचा वॉर्ड निवडा',
  localityPickerHint: 'तुमचा परिसर निवडा',
  completeBtn: 'नोंदणी पूर्ण करा',
  completing: 'पूर्ण होत आहे…',
  mobileError: 'कृपया 6-9 ने सुरू होणारा वैध 10-अंकी मोबाइल क्रमांक प्रविष्ट करा',
  otpError: 'कृपया संपूर्ण 6-अंकी OTP प्रविष्ट करा.',
  nameError: 'कृपया तुमचे पूर्ण नाव प्रविष्ट करा.',
  wardError: 'कृपया तुमचा वॉर्ड निवडा.',
  localityError: 'कृपया तुमचा परिसर निवडा.',

  // Settings (citizen)
  settingsTitle: 'सेटिंग्ज',
  complaintUpdates: 'तक्रार अद्यतने',
  councilAnnouncements: 'परिषद घोषणा',
  smsAlerts: 'SMS सूचना',

  // Profile (citizen)
  profileTitle: 'माझी प्रोफाइल',
  mobileNumber: 'मोबाइल क्रमांक',
  mobilePlaceholder2: 'उदा. 9876543210',
  localityAreaStreet: 'परिसर / क्षेत्र / रस्ता',
  localityPlaceholder: 'उदा. वायरी बाजार',
  municipality: 'नगरपालिका',
  saveChangesBtn: 'बदल जतन करा',
  savingChanges: 'बदल जतन होत आहेत…',
  logoutBtn: 'लॉगआउट',
  loggingOut: 'लॉगआउट होत आहे…',
  appMenuTitle: 'अॅप मेनू',
  helpFaqs: 'मदत व विचारले जाणारे प्रश्न',
  privacyPol: 'गोपनीयता धोरण',
  termsCond: 'अटी व शर्ती',
  aboutApp: 'सेवा सेतू बद्दल',
  appVer: 'अॅप आवृत्ती',
  settingsMenu: 'सेटिंग्ज',

  // ── Auth / Splash ─────────────────────────────────────────────────────────
  splashSlogan: 'नागरिकांना जोडणे. समस्या सोडवणे.',
  splashSkip: 'वगळा →',

  // ── Role Selection ────────────────────────────────────────────────────────
  welcomeMalvan: 'मालवणमध्ये स्वागत आहे',
  roleSelectHint: 'नगरपालिका सेवांशी जोडण्यासाठी तुमचे लॉगिन प्रोफाइल निवडा.',
  roleCitizen: 'नागरिक लॉगिन',
  roleCitizenDesc: 'समस्या नोंदवा आणि प्रगती ट्रॅक करा',
  roleNagarsevak: 'नगरसेवक लॉगिन',
  roleNagarsevakDesc: 'प्रतिनिधी शासन पोर्टल',
  roleDepartment: 'विभाग लॉगिन',
  roleDepartmentDesc: 'नियुक्त नागरी अहवाल सोडवा',
  roleAdmin: 'प्रशासक लॉगिन',
  roleAdminDesc: 'नगरपालिका नियंत्रण आणि सेटिंग्ज',

  // ── Admin Login ───────────────────────────────────────────────────────────
  restrictedPortal: 'प्रतिबंधित पोर्टल',
  adminLoginHint: 'नगराध्यक्ष पोर्टलमध्ये प्रवेश करण्यासाठी अधिकृत क्रेडेन्शियल वापरा.',
  adminId: 'प्रशासक आयडी',
  adminIdPlaceholder: 'प्रशासक आयडी प्रविष्ट करा',
  loginToAdminPortal: 'प्रशासक पोर्टलमध्ये लॉगिन करा',
  securedEncryption: '256-बिट एन्क्रिप्शनसह सुरक्षित',

  // ── Nagarsevak Login ──────────────────────────────────────────────────────
  nagarsevakLogin: 'नगरसेवक लॉगिन',
  nagarsevakLoginSubtitle: 'वॉर्ड-स्तरीय नगरपालिका डॅशबोर्डमध्ये प्रवेश करा.',
  signInToContinue: 'सुरू ठेवण्यासाठी साइन इन करा',
  nagarsevakLoginHint: 'नगरसेवक पोर्टल उघडण्यासाठी तुमचे वॉर्ड अधिकारी क्रेडेन्शियल वापरा.',
  officialId: 'अधिकृत आयडी',
  officialIdPlaceholder: 'अधिकृत आयडी प्रविष्ट करा',
  wardLabel2: 'वॉर्ड',
  wardPlaceholder: 'वॉर्ड प्रविष्ट करा',
  passwordLabel: 'पासवर्ड',
  passwordPlaceholder: 'पासवर्ड प्रविष्ट करा',
  login: 'लॉगिन',

  // ── Official / Nagarsevak Dashboard ───────────────────────────────────────
  wardOverview: 'वॉर्ड आढावा',
  performanceGlance: 'एका दृष्टिक्षेपात कामगिरी',
  todaysUpdates: 'आजचे अपडेट',
  monthlyPerformance: 'मासिक कामगिरी',
  avgResolution: 'सरासरी निराकरण',
  emergencyHighPriority: 'आणीबाणी आणि उच्च प्राधान्य',
  allClear: 'सर्व ठीक आहे!',
  noUrgentComplaints: 'सध्या कोणत्याही तातडीच्या तक्रारी प्रलंबित नाहीत.',
  nagarsevakDesignation: 'नगरसेवक (वॉर्ड प्रतिनिधी)',
  municipalAlerts: 'नगरपालिका सूचना आणि परिषद नोटिसा',
  noAnnouncementsTab: 'कोणत्याही घोषणा नाहीत',
  noNoticesTime: 'यावेळी कोणत्याही {tab} नोटिसा नाहीत.',

  // ── Official Complaints screen ────────────────────────────────────────────
  wardComplaintsTitle: 'वॉर्ड तक्रारी',
  nagarsevakWardReview: 'नगरसेवक वॉर्ड आढावा',
  searchPlaceholderOfficial: 'आयडी, शीर्षक, नागरिक किंवा ठिकाणाने शोधा…',
  noMatchingComplaints: 'जुळणाऱ्या तक्रारी नाहीत',
  adjustFilters: 'तुमचा शोध किंवा फिल्टर समायोजित करण्याचा प्रयत्न करा.',
  complaintsFound: 'तक्रारी आढळल्या',
  complaintFound: 'तक्रार आढळली',

  // ── Official Complaint Details ─────────────────────────────────────────────
  complaintSummary: 'तक्रार सारांश',
  complaintNotFound: 'तक्रार आढळली नाही',
  complaintNotFoundDesc: 'या वॉर्डात तक्रार संदर्भ आयडी अस्तित्वात नाही.',
  goBack: 'परत जा',
  filedOn: 'दाखल',
  updatedOn: 'अद्यतनित',
  citizenInformation: 'नागरिक माहिती',
  complaintDetailsSection: 'तक्रार तपशील',
  attachedPhotos: 'जोडलेले फोटो',
  uploadBtn: 'अपलोड',
  noPhotosYet: 'अद्याप कोणतेही फोटो जोडलेले नाहीत.',
  timeline: 'टाइमलाइन',
  addNoteBtn: 'नोंद जोडा',
  notes: 'नोंदी',
  actions: 'कृती',
  escalateComplaint: 'तक्रार वर्ग करा',
  complaintRegisteredEvent: 'तक्रार नोंदणी झाली',
  assignedToDept: 'विभागाला नियुक्त',
  routedTo: 'पाठवले',
  actionTaken: 'कृती केली',
  successUpload: 'यशस्वी',
  successUploadMsg: 'सत्यापन फोटो अपलोड केला.',
  statusUpdated: 'अद्यतनित',
  statusUpdatedMsg: 'स्थिती बदलली',

  // ── Official Profile ───────────────────────────────────────────────────────
  tapToChangeProfilePic: 'प्रोफाइल फोटो बदलण्यासाठी टॅप करा',
  officialDemographicsSection: 'अधिकृत लोकसंख्याशास्त्र',
  roleAndWardNote: 'भूमिका आणि वॉर्ड माहिती तुमच्या नगरपरिषद नोंदणीतून जोडलेली आहे.',
  saving: 'जतन होत आहे…',
  saveChangesProfile: 'बदल जतन करा',
  loggingOutLabel: 'लॉगआउट होत आहे…',
  logoutLabel: 'लॉगआउट',
  validationTitle: 'वैधता',
  nameRequired: 'पूर्ण नाव आवश्यक आहे.',
  phoneRequired: 'फोन नंबर आवश्यक आहे.',
  profileUpdated: 'प्रोफाइल यशस्वीरित्या अद्यतनित केली.',
  profileUpdateError: 'प्रोफाइल जतन करणे अयशस्वी. कृपया पुन्हा प्रयत्न करा.',
  photoUploadNote: 'बॅकएंड एकत्रीकरणानंतर फोटो पिकर उपलब्ध होईल.',

  // ── Official Settings ─────────────────────────────────────────────────────
  grievanceAssignments: 'तक्रार नियुक्त्या',
  grievanceAssignmentsDesc: 'एखाद्या नागरिकाने तुमच्या वॉर्डात तक्रार दाखल केल्यावर सूचना.',
  councilAnnouncementsLabel: 'परिषद घोषणा',
  councilAnnouncementsDesc: 'मुख्य प्रशासक नोटिस प्रकाशित करतो तेव्हा सूचना.',
  smsAlertBroadcasts: 'SMS सूचना प्रसारण',
  smsAlertBroadcastsDesc: 'आणीबाणी सूचनांसाठी मजकूर सूचना.',
  weeklyEmailSummary: 'साप्ताहिक ईमेल सारांश',
  weeklyEmailSummaryDesc: 'दर आठवड्याला वॉर्ड निराकरण आकडेवारीचा सारांश.',
  alertPreferences: 'सूचना प्राधान्ये',
  selectTheme: 'थीम निवडा',
  accessibilityLabel: 'प्रवेशयोग्यता',
  highContrastMode: 'उच्च कॉन्ट्रास्ट मोड',
  highContrastDesc: 'चांगल्या वाचनीयतेसाठी मजकूर कॉन्ट्रास्ट वाढवतो.',
  reduceMotion: 'गती कमी करा',
  reduceMotionDesc: 'स्लाइड-इन अॅनिमेशन आणि ट्रांझिशन अक्षम करतो.',
  generalSettings: 'सामान्य सेटिंग्ज',
  biometricAuth: 'बायोमेट्रिक प्रमाणीकरण',
  biometricDesc: 'FaceID/Fingerprint वापरून त्वरीत लॉगिन करा.',
  autoLogout: 'स्वयं लॉगआउट सत्र',
  autoLogoutDesc: '30 मिनिटे निष्क्रियतेनंतर लॉग आउट करा.',

  // ── About Screen ──────────────────────────────────────────────────────────
  officialGovernancePortal: 'अधिकृत शासन पोर्टल · v1.0.0',
  connectingMalvan: 'मालवणला जोडणे',
  connectingMalvanBody1: 'सेवा सेतू हे मालवण नागरिक आणि त्यांचे निवडून आलेले वॉर्ड प्रतिनिधी (नगरसेवक) आणि नगरपालिका प्रशासन अधिकारी यांना जोडणारा अधिकृत डिजिटल पूल आहे.',
  connectingMalvanBody2: 'स्थानिक वॉर्ड लोकसंख्याशास्त्र आणि रिअल-टाइम तक्रार नोंदी वापरून, पोर्टल प्रशासकीय जबाबदारी, सार्वजनिक पारदर्शकता आणि नागरी कार्यांसाठी त्वरित निराकरण सुनिश्चित करते.',
  officialRecognition: 'अधिकृत मान्यता',
  officialRecognitionBody: 'हे अॅप्लिकेशन नोड मालवण नगरपरिषदेच्या डेस्कशी थेट समक्रमित आहे. सर्व क्रियाकलाप, तक्रार अहवाल आणि कामगिरी मापदंड सुरक्षितपणे सार्वजनिक प्रशासकीय देखरेखीच्या नियमांनुसार नोंदवले जातात.',
  citizenGrievanceNode: 'नागरिक तक्रार निराकरण नोड • v1.0.0',
  connectingMalvanCitizen: 'मालवणला जोडणे',
  connectingMalvanCitizenBody: 'सेवा सेतू मालवण नागरिक आणि नगरपालिका प्रशासन यांच्यातील अधिकृत संवाद पूल म्हणून काम करते. स्थानिक वॉर्ड समस्या नोंदवून, नागरिक नगरपालिकेला त्वरित कार्य करण्यास आणि पायाभूत सुविधा पारदर्शकपणे राखण्यास सक्षम करतात.',
  officialCouncilNode: 'अधिकृत परिषद नोड',
  officialCouncilNodeBody: 'सर्व तक्रारी, डेटा आणि ट्रॅकिंग मालवण नगरपरिषदेच्या डेस्कशी थेट समक्रमित आहेत. प्रवेश अधिकृत सार्वजनिक डेटा संरक्षण नियमांनुसार नियंत्रित आहे.',
  meetOurTeam: 'आमच्या टीमशी भेटा',
  meetOurTeamSub: 'सेवा सेतूच्या मागे असलेले लोक, मालवणच्या नागरी सेवा सोपी आणि जलद करण्यासाठी काम करत आहेत.',
  footerCopyright: '© 2026 मालवण नगरपरिषद • महाराष्ट्र सरकार',

  // ── Admin Dashboard ───────────────────────────────────────────────────────
  liveStats: 'लाइव्ह शहर आकडेवारी',
  realTimeOverview: 'रिअल-टाइम नगरपालिका आढावा',
  exploreComplaints: 'तक्रारी शोधा',
  drillData: 'शहर-व्यापी डेटामध्ये खोलात जा',
  quickActions: 'जलद कृती',
  viewAllComplaints: 'सर्व तक्रारी पहा',
  bestWards: 'सर्वोत्कृष्ट वॉर्ड',
  performanceRanking: 'कामगिरी क्रमवारी',
  wardWiseLabel: 'वॉर्डनिहाय',
  allMunicipalWards: 'सर्व १० नगरपालिका वॉर्ड',
  categoryWiseLabel: 'वर्गनिहाय',
  byIssueType: 'समस्येच्या प्रकारानुसार',
  departmentWiseLabel: 'विभागनिहाय',
  resolutionByDept: 'विभागानुसार निराकरण',

  // ── Admin Announcements ───────────────────────────────────────────────────
  announcementsScreen: 'घोषणा',
  composeTab: 'तयार करा',
  publishedTab: 'प्रकाशित',
  announcementTitle: 'घोषणा शीर्षक',
  announcementTitlePlaceholder: 'स्पष्ट, संक्षिप्त शीर्षक प्रविष्ट करा…',
  messageBody: 'संदेश मजकूर',
  messageBodyPlaceholder: 'संपूर्ण घोषणा मजकूर…',
  priorityLevel: 'प्राधान्य स्तर',
  targetAudience: 'लक्ष्य प्रेक्षक',
  sendAnnouncement: 'घोषणा पाठवा',
  noAnnouncementsYet: 'अद्याप कोणत्याही घोषणा नाहीत',
  missingInfo: 'माहिती अपूर्ण',
  fillTitleMessage: 'कृपया शीर्षक आणि संदेश दोन्ही भरा.',
  scheduleComingSoon: 'वेळापत्रक (लवकरच येत आहे)',
  attachFile: 'फाइल जोडा',
  previewLabel: 'पूर्वावलोकन',
  hidePreview: 'पूर्वावलोकन लपवा',

  // ── Admin Complaints ──────────────────────────────────────────────────────
  searchComplaintsAdmin: 'आयडी, शीर्षक, नागरिक, ठिकाणाने शोधा…',
  noMatchingComplaintsAdmin: 'जुळणाऱ्या तक्रारी नाहीत',
  adjustFiltersAdmin: 'तुमचा शोध किंवा फिल्टर समायोजित करा.',
  addNoteTitle: 'नोंद जोडा',
  restrictUser: 'वापरकर्ता प्रतिबंधित करा',
  blockUser: 'वापरकर्ता ब्लॉक करा',
  removeComplaint: 'तक्रार काढा',
  confirmAction: 'पुष्टी करा',

  // ── Department Dashboard ──────────────────────────────────────────────────
  welcomeBack: 'पुन्हा स्वागत आहे,',
  allWardsWorkspace: 'सर्व १० वॉर्ड · विभाग कार्यक्षेत्र',
  filterByWard: 'वॉर्डनुसार फिल्टर करा',
  tapWardFilter: 'तक्रारी पाहण्यासाठी वॉर्डवर टॅप करा. साफ करण्यासाठी पुन्हा टॅप करा.',
  allWardsChip: 'सर्व वॉर्ड',
  resolutionRate: 'निराकरण दर',
  resolvedOf: 'एकूण',
  total: 'पैकी निकाली',
  pendingComplaints: 'प्रलंबित तक्रारी',
  allCaughtUp: 'सर्व काम संपले!',
  noPendingComplaints: 'सध्या कोणत्याही प्रलंबित तक्रारी नाहीत',
  rightNow: 'आत्ता.',
  reviewAllComplaints: 'सर्व तक्रारींचा आढावा घ्या',
  deptOnlyReporting: 'केवळ विभाग अहवाल · सर्व वॉर्ड',
  monthlyPerformanceLabel: 'मासिक कामगिरी',

  // ── Department Complaints ─────────────────────────────────────────────────
  searchDeptComplaints: 'या विभागाच्या तक्रारी शोधा',
  deptComplaintsScope: 'सर्व वॉर्ड',
  noDeptComplaints: 'कोणत्याही जुळणाऱ्या विभाग तक्रारी नाहीत.',

  // ── Department Announcements ──────────────────────────────────────────────
  readOnlyNotice: 'मुख्य प्रशासकाद्वारे (नगराध्यक्ष) प्रकाशित नोटिसा · केवळ वाचनीय',
  noAnnouncementsMsg: 'कोणत्याही घोषणा नाहीत',
  noNoticesPublished: 'अद्याप कोणत्याही {tab} नोटिसा प्रकाशित केल्या नाहीत.',

  // ── Ward Screen ────────────────────────────────────────────────────────────
  officialDemographicsHeader: 'अधिकृत लोकसंख्याशास्त्र',
  wardRepsSection: 'वॉर्ड प्रतिनिधी (नगरसेवक)',
  callWardRep: 'वॉर्ड प्रतिनिधींना कॉल करा',
  issuesResolvedWard: '% समस्या या वॉर्डात सोडवल्या',

  // ── Leaderboard ───────────────────────────────────────────────────────────
  wardLeaderboard: 'वॉर्ड लीडरबोर्ड',
  leaderboardTitle: 'स्वच्छ आणि जलद वॉर्ड क्रमवारी',
  leaderboardBody: 'वॉर्ड निराकरण दर, सार्वजनिक स्वच्छता रेटिंग आणि फीडबॅक नोंदींच्या आधारे गतिशीलपणे क्रमवारी लावले जातात.',
  rankLabel: 'क्रमांक',
  wardRepLabel: 'वॉर्ड आणि प्रतिनिधी',
  resolutionRateLabel: 'निराकरण दर',

  // ── Help Screen ───────────────────────────────────────────────────────────
  helpSupport: 'मदत आणि सहाय्य',
  frequentlyAsked: 'वारंवार विचारले जाणारे प्रश्न',
  howToReportTrack: 'कसे नोंदवायचे आणि ट्रॅक करायचे',
  contactMunicipalCouncil: 'नगरपालिका परिषदाशी संपर्क करा',
  contactIntro: 'वॉर्ड समस्या किंवा सामान्य नगरपालिका सेवांसाठी थेट मदत हवी असल्यास खाली संपर्क करा.',
  callSupport: 'कॉल सहाय्य: 02365-252018',
  emailSupport: 'ईमेल: support@malvanmunicipal.in',
  portalFooter: 'मालवण नगरपरिषद सेवा सेतू पोर्टल v1.0.0',

  // ── Dept Help FAQs ────────────────────────────────────────────────────────
  tapToExpand: 'उत्तर विस्तारण्यासाठी कोणत्याही प्रश्नावर टॅप करा.',
  themeLight: 'हलका',
  themeDark: 'गडद',
  themeSystem: 'सिस्टम',
  cancel: 'रद्द करा',
  logoutConfirmation: 'तुम्ही लॉगआउट करण्याची खात्री आहे का?',
  logoutCitizenConfirmation: 'सेवा सेतूमधून लॉगआउट करायचे का?',
  logoutDepartmentConfirmation: 'विभाग अधिकारी पोर्टलमधून साइन आउट करायचे का?',
  restrictedAccess: 'मर्यादित प्रवेश',
  tapToFill: 'भरण्यासाठी टॅप करा',
  secureEncryption: '256-बिट एन्क्रिप्शनसह सुरक्षित',
  unableToSignIn: 'साइन इन करता आले नाही.',
  enterOtp: 'OTP प्रविष्ट करा',
  change: 'बदला',
  canResendNow: 'आता पुन्हा पाठवू शकता',
  createCitizenProfile: 'नागरिक प्रोफाइल तयार करा',
  addressVerificationHint: 'कृपया मालवणमधील तुमच्या अधिकृत पत्त्याशी जुळणारी माहिती द्या.',
  localityStreetLandmark: 'परिसर / रस्ता / ओळखखूण',
  localityExample: 'उदा. मेधा, वायरी रोड',
  selectResidenceWard: 'कृपया तुमच्या निवासाचा नगरपालिका वॉर्ड निवडा.',
  enterWard: 'वॉर्ड प्रविष्ट करा',
  departmentLoginHint: 'तुमचा विभाग निवडा, नंतर अधिकृत क्रेडेन्शियलसह साइन इन करा.',
  municipalDepartment: 'नगरपालिका विभाग',
  demoCredentialsTapToFill: 'डेमो क्रेडेन्शियल — भरण्यासाठी टॅप करा',
  usernamePlaceholder: 'वापरकर्ता नाव प्रविष्ट करा',
  error: 'त्रुटी',
  success: 'यशस्वी',
  profileUpdatedToast: 'प्रोफाइल यशस्वीरित्या अद्यतनित केले.',
  profileUpdateFailed: 'प्रोफाइल अद्यतनित करता आले नाही.',
};

const KEY = '@seva-setu/language';

type Value = {
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => Promise<void>;
  t: (key: string) => string;
};

const LocalizationContext = createContext<Value | undefined>(undefined);

export function LocalizationProvider({ children }: PropsWithChildren) {
  const [language, setLanguageState] = useState<AppLanguage>('English');

  useEffect(() => {
    void AsyncStorage.getItem(KEY).then((saved) => {
      if (saved === 'Marathi' || saved === 'English') {
        setLanguageState(saved);
      }
    });
  }, []);

  const setLanguage = async (next: AppLanguage) => {
    setLanguageState(next);
    await AsyncStorage.setItem(KEY, next);
  };

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key: string) => {
        const transKey = key as keyof typeof en;
        return (language === 'Marathi' ? mr[transKey] : en[transKey]) || en[transKey] || key;
      },
    }),
    [language]
  );

  return <LocalizationContext.Provider value={value}>{children}</LocalizationContext.Provider>;
}

export function useTranslation() {
  const context = useContext(LocalizationContext);
  if (!context) {
    throw new Error('useTranslation must be used inside LocalizationProvider.');
  }
  return context;
}
