import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import type { PropsWithChildren } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { COLORS } from '@/constants/theme';
import { useDepartment } from '@/providers/department-provider';
const tabs = [['dashboard', 'home-variant-outline', 'Dashboard'], ['complaints', 'clipboard-text-outline', 'Complaints'], ['announcements', 'bullhorn-outline', 'Announcements'], ['analytics', 'chart-bar', 'Analytics'], ['profile', 'account-outline', 'Profile']] as const;
export function DepartmentScreen({ title, tab, back, children }: PropsWithChildren<{ title: string; tab?: string; back?: boolean }>) { const router = useRouter() as any; const { profile } = useDepartment(); return <View style={styles.root}><SafeAreaView edges={['top']} style={styles.safe}><View style={styles.header}>{back ? <Pressable onPress={() => router.back()} style={styles.headButton}><MaterialCommunityIcons name="arrow-left" size={23} color={COLORS.white}/></Pressable> : <View style={styles.headButton}/>}<Text style={styles.title}>{title}</Text><Pressable onPress={() => router.push('/(dept)/profile')} style={styles.avatar}><Text style={styles.avatarText}>{profile?.avatarInitial ?? 'D'}</Text></Pressable></View></SafeAreaView><View style={styles.body}>{children}</View>{!back && <SafeAreaView edges={['bottom']} style={styles.nav}><View style={styles.navRow}>{tabs.map(([route, icon, label]) => <Pressable key={route} onPress={() => router.replace(`/(dept)/${route}` as never)} style={styles.tab}><MaterialCommunityIcons name={icon} size={22} color={tab === route ? COLORS.primary : COLORS.textMuted}/><Text style={[styles.tabText, tab === route && styles.tabActive]}>{label}</Text></Pressable>)}</View></SafeAreaView>}</View>; }
const styles = StyleSheet.create({ root:{flex:1,backgroundColor:COLORS.background},safe:{backgroundColor:COLORS.primary},header:{height:58,paddingHorizontal:16,alignItems:'center',flexDirection:'row',backgroundColor:COLORS.primary},headButton:{width:36,height:36,alignItems:'center',justifyContent:'center'},title:{flex:1,textAlign:'center',color:COLORS.white,fontSize:18,fontWeight:'800'},avatar:{width:36,height:36,borderRadius:18,backgroundColor:COLORS.warning,alignItems:'center',justifyContent:'center'},avatarText:{color:COLORS.white,fontWeight:'800'},body:{flex:1},nav:{backgroundColor:COLORS.card,borderTopWidth:1,borderTopColor:COLORS.border},navRow:{flexDirection:'row',justifyContent:'space-around',paddingTop:8},tab:{alignItems:'center',width:'20%',gap:3,paddingBottom:5},tabText:{fontSize:9.5,fontWeight:'600',color:COLORS.textMuted},tabActive:{color:COLORS.primary,fontWeight:'800'} });
