// @ts-nocheck
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import Animated, { FadeInDown } from 'react-native-reanimated';
import { AuthHero, AuthSheet } from '@/components/common/AuthScaffold';
import CustomTextInput from '@/components/common/CustomTextInput';
import PrimaryButton from '@/components/common/PrimaryButton';
import { COLORS, TYPOGRAPHY } from '@/constants/theme';
import { ALL_DEPARTMENTS } from '@/data/complaints';
import { DEPT_META } from '@/data/department-routing';
import { useDepartment } from '@/providers/department-provider';
import { DEPT_DEMO_CREDENTIALS, loginDemoDepartmentOfficer } from '@/services/auth';

export default function DepartmentLoginScreen() {
  const router = useRouter(); const { login } = useDepartment();
  const [department, setDepartment] = useState<string>(); const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [remember, setRemember] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const credential = DEPT_DEMO_CREDENTIALS.find((item) => item.deptName === department);
  const submit = async () => { if (!department || !username || !password) return; setLoading(true); setError(''); try { await login(loginDemoDepartmentOfficer(department, username, password)); router.replace('/(dept)/dashboard'); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to sign in.'); } finally { setLoading(false); } };
  return <View style={styles.root}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><AuthHero title="Department Officer Login" subtitle="Malvan Municipal Council — Department Portal" badge="DEPARTMENT ACCESS" icon="office-building-outline" showLogo onBack={() => router.back()} compact/><AuthSheet><ScrollView showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}><Animated.View entering={FadeInDown.duration(350)}><Text style={styles.heading}>Select Department</Text><Text style={styles.hint}>Choose your department, then use its authorised credentials.</Text></Animated.View><View style={styles.departments}>{ALL_DEPARTMENTS.map((name, index) => { const selected = department === name; const meta = DEPT_META[name]; return <Animated.View entering={FadeInDown.duration(300).delay(index * 35)} key={name}><Pressable onPress={() => { setDepartment(name); setUsername(''); setPassword(''); setError(''); }} style={[styles.department, selected && styles.departmentSelected]}><View style={[styles.icon, {backgroundColor: meta?.bg ?? '#EAF3FF'}]}><MaterialCommunityIcons name={(meta?.icon ?? 'office-building-outline') as never} size={19} color={meta?.color ?? COLORS.primary}/></View><View style={{flex:1}}><Text style={styles.departmentName}>{name}</Text><Text style={styles.departmentSub}>{meta?.english ?? 'Municipal Department'}</Text></View>{selected && <MaterialCommunityIcons name="check-circle" size={21} color={COLORS.primary}/>}</Pressable></Animated.View>; })}</View>{department && credential && <Animated.View entering={FadeInDown.duration(260)}><Pressable onPress={() => { setUsername(credential.username); setPassword(credential.password); }} style={styles.demo}><Text style={styles.demoTitle}>Demo Credentials · Tap to fill</Text><Text style={styles.demoText}>Username: {credential.username}</Text><Text style={styles.demoText}>Password: {credential.password}</Text></Pressable><CustomTextInput icon="account-outline" label="Username" placeholder="Enter username" value={username} onChangeText={(value) => {setUsername(value);setError('');}} autoCapitalize="none"/><CustomTextInput icon="lock-outline" label="Password" placeholder="Enter password" value={password} onChangeText={(value) => {setPassword(value);setError('');}} secureTextEntry/><Pressable onPress={() => setRemember(!remember)} style={styles.remember}><MaterialCommunityIcons name={remember ? 'checkbox-marked' : 'checkbox-blank-outline'} size={22} color={COLORS.primary}/><Text style={styles.rememberText}>Remember me</Text></Pressable>{error ? <Text style={styles.error}>{error}</Text> : null}<PrimaryButton label={loading ? 'Signing in…' : 'Login'} loading={loading} disabled={!username || !password || loading} onPress={submit} style={styles.button}/></Animated.View>}</ScrollView></AuthSheet></KeyboardAvoidingView></View>;
}
const styles = StyleSheet.create({root:{flex:1,backgroundColor:'#081B2B'},content:{paddingHorizontal:24,paddingTop:8,paddingBottom:32},heading:{...TYPOGRAPHY.h2,color:COLORS.primary},hint:{...TYPOGRAPHY.caption,color:COLORS.textMuted,marginTop:5,marginBottom:16},departments:{gap:9},department:{flexDirection:'row',alignItems:'center',gap:11,padding:12,borderWidth:1,borderColor:COLORS.border,borderRadius:16,backgroundColor:COLORS.card},departmentSelected:{borderColor:COLORS.primary,backgroundColor:'#F4F8FF'},icon:{width:40,height:40,borderRadius:12,alignItems:'center',justifyContent:'center'},departmentName:{fontSize:13,fontWeight:'800',color:COLORS.text},departmentSub:{fontSize:11.5,color:COLORS.textMuted,marginTop:2},demo:{marginTop:18,marginBottom:8,borderRadius:14,padding:13,backgroundColor:'#FFF8EB',borderWidth:1,borderColor:'#F6E0B2'},demoTitle:{fontWeight:'800',fontSize:12,color:'#A66A00',marginBottom:3},demoText:{fontSize:12,color:'#7D5A00',lineHeight:18},remember:{flexDirection:'row',alignItems:'center',gap:7,marginTop:5},rememberText:{fontSize:13,color:COLORS.textMuted,fontWeight:'600'},error:{color:COLORS.danger,fontSize:13,fontWeight:'600',marginTop:12},button:{marginTop:18}});
