import { MaterialCommunityIcons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { CITIZEN_COLORS as C, LOCALITIES, WARDS } from '@/constants/citizen';
import { useCitizen } from '@/providers/citizen-provider';
export default function CompleteProfile() { const router=useRouter(); const {saveProfile}=useCitizen(); const [name,setName]=useState(''); const [ward,setWard]=useState(''); const [locality,setLocality]=useState(''); const complete=async()=>{if(!name.trim()||!ward||!locality)return;await saveProfile({name:name.trim(),phone:'',ward,locality,address:''});router.replace('/dashboard');}; return <SafeAreaView style={p.root}><View style={p.hero}><MaterialCommunityIcons name="account-check-outline" size={38} color={C.saffron}/><Text style={p.heroTitle}>Complete your profile</Text><Text style={p.heroText}>Your ward and locality make sure every complaint reaches the right team.</Text></View><ScrollView contentContainerStyle={p.sheet}><Text style={p.label}>Full name</Text><TextInput value={name} onChangeText={setName} placeholder="Enter your full name" style={p.input}/><Text style={p.label}>Select ward</Text><View style={p.options}>{WARDS.map(value=><Pressable key={value} onPress={()=>{setWard(value);setLocality('');}} style={[p.chip,ward===value&&p.active]}><Text style={[p.chipText,ward===value&&p.activeText]}>{value}</Text></Pressable>)}</View>{ward&&<><Text style={p.label}>Select locality</Text><View style={p.options}>{LOCALITIES[ward].map(value=><Pressable key={value} onPress={()=>setLocality(value)} style={[p.chip,locality===value&&p.active]}><Text style={[p.chipText,locality===value&&p.activeText]}>{value}</Text></Pressable>)}</View></>}<Pressable onPress={complete} disabled={!name.trim()||!ward||!locality}><LinearGradient colors={[C.navy,C.blue]} style={p.button}><Text style={p.buttonText}>Continue to dashboard</Text></LinearGradient></Pressable></ScrollView></SafeAreaView>; }
const p=StyleSheet.create({root:{flex:1,backgroundColor:C.bg},hero:{backgroundColor:C.navy,padding:28,paddingTop:46},heroTitle:{color:C.white,fontSize:23,fontWeight:'800',marginTop:12},heroText:{color:'rgba(255,255,255,0.8)',lineHeight:20,marginTop:6},sheet:{padding:24},label:{fontWeight:'800',color:C.text,marginTop:10,marginBottom:9},input:{height:54,borderRadius:14,borderWidth:1,borderColor:C.border,backgroundColor:C.card,paddingHorizontal:15,fontSize:15},options:{flexDirection:'row',flexWrap:'wrap',gap:9},chip:{paddingVertical:10,paddingHorizontal:13,borderRadius:20,borderWidth:1,borderColor:C.border,backgroundColor:C.card},active:{backgroundColor:C.navy,borderColor:C.navy},chipText:{color:C.navy,fontWeight:'600'},activeText:{color:C.white},button:{height:54,borderRadius:14,alignItems:'center',justifyContent:'center',marginTop:32},buttonText:{color:C.white,fontSize:16,fontWeight:'800'}});
