import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useMemo, useState } from 'react';
import { Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import ComplaintCard from '@/components/official/ComplaintCard';
import { AdminShell } from '@/components/admin/admin-shell';
import { useOfficial } from '@/providers/official-provider';

const statuses = ['All', 'Pending', 'In Progress', 'Resolved']; const priorities = ['All', 'Emergency', 'High', 'Medium', 'Low'];
export default function AdminComplaints() { const router = useRouter(); const params = useLocalSearchParams<{ ward?: string; category?: string; department?: string; status?: string; escalated?: string }>(); const { complaints } = useOfficial(); const [search, setSearch] = useState(''); const [status, setStatus] = useState(params.status ?? 'All'); const [priority, setPriority] = useState('All');
  const filtered = useMemo(() => complaints.filter(c => { const haystack = `${c.id} ${c.title} ${c.citizenName} ${c.location}`.toLowerCase(); return haystack.includes(search.toLowerCase()) && (!params.ward || c.ward.startsWith(params.ward)) && (!params.category || c.category === params.category) && (!params.department || c.assignedDepartment === params.department) && (status === 'All' || c.status === status) && (priority === 'All' || c.priority === priority) && (!params.escalated || c.notes.some(n => /escalated/i.test(n.text))); }), [complaints, params, priority, search, status]);
  const Chip = ({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) => <Pressable onPress={onPress} className={`px-3 py-2 rounded-full mr-2 ${selected ? 'bg-blue-600' : 'bg-slate-100'}`}><Text className={`text-xs font-bold ${selected ? 'text-white' : 'text-slate-600'}`}>{label}</Text></Pressable>;
  return <AdminShell title="Complaints"><ScrollView contentContainerStyle={{ padding: 16, paddingBottom: 42 }}><View className="bg-white border border-slate-100 rounded-2xl flex-row items-center px-3 py-2 mb-3"><Ionicons name="search-outline" size={20} color="#64748B"/><TextInput value={search} onChangeText={setSearch} placeholder="Search complaints" className="flex-1 ml-2 text-slate-800" /></View><Text className="text-xs font-bold text-slate-500 mb-2">Status</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} className="mb-3">{statuses.map(x => <Chip key={x} label={x} selected={status === x} onPress={() => setStatus(x)} />)}</ScrollView><Text className="text-xs font-bold text-slate-500 mb-2">Priority</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} className="mb-5">{priorities.map(x => <Chip key={x} label={x} selected={priority === x} onPress={() => setPriority(x)} />)}</ScrollView><Text className="text-sm text-slate-500 mb-3">{filtered.length} matching complaints</Text>{filtered.map(c => <ComplaintCard key={c.id} complaint={c} onView={() => router.push({ pathname: '/(official)/complaint-details', params: { id: c.id } } as any)} onNotes={() => router.push({ pathname: '/(official)/add-note', params: { id: c.id } } as any)} onEscalate={() => router.push({ pathname: '/(official)/escalate', params: { id: c.id } } as any)} />)}</ScrollView></AdminShell>; }
